#ifndef __ICEBOARD_H__
#define __ICEBOARD_H__

typedef struct iceboard {

} iceboard;

/* Units */
/*#define UNIT_VOLTS			"UNIT_VOLTS"
#define UNIT_AMPS			"UNIT_AMPS"
#define UNIT_WATTS			"UNIT_WATTS"*/

/* Temperature sensors */
#define MOTHERBOARD_TEMPERATURE_POWER	"MOTHERBOARD_TEMPERATURE_POWER"
#define MOTHERBOARD_TEMPERATURE_ARM	"MOTHERBOARD_TEMPERATURE_ARM"
#define MOTHERBOARD_TEMPERATURE_FPGA	"MOTHERBOARD_TEMPERATURE_FPGA"
#define MOTHERBOARD_TEMPERATURE_PHY	"MOTHERBOARD_TEMPERATURE_ARM"

/* Motherboard power rails */
#define MOTHERBOARD_RAIL_VCC3V3		"MOTHERBOARD_RAIL_VCC3V3"
#define MOTHERBOARD_RAIL_VCC12V0	"MOTHERBOARD_RAIL_VCC12V0"
#define MOTHERBOARD_RAIL_VCC5V5		"MOTHERBOARD_RAIL_VCC5V5"
#define MOTHERBOARD_RAIL_VCC1V0_GTX	"MOTHERBOARD_RAIL_VCC1V0_GTX"
#define MOTHERBOARD_RAIL_VCC1V0		"MOTHERBOARD_RAIL_VCC1V0"
#define MOTHERBOARD_RAIL_VCC1V2		"MOTHERBOARD_RAIL_VCC1V2"
#define MOTHERBOARD_RAIL_VCC1V5		"MOTHERBOARD_RAIL_VCC1V5"
#define MOTHERBOARD_RAIL_VCC1V8		"MOTHERBOARD_RAIL_VCC1V8"
#define MOTHERBOARD_RAIL_VADJ		"MOTHERBOARD_RAIL_VADJ"

#define MEZZANINE_RAIL_VCC3V3		"MEZZANINE_RAIL_VCC3V3"
#define MEZZANINE_RAIL_VCC12V0		"MEZZANINE_RAIL_VCC12V0"
#define MEZZANINE_RAIL_VADJ		"MEZZANINE_RAIL_VADJ"


#endif
