connection_config:
    prog: 1                 # 0 - do not reprogram, 1 - reprogram if outdated, 2 - always reprogram
    mode: 'corr16'          # Do not change for a single board
    hwm: 'mb 257'           # For a different board change the serial number

test_config:
    loglevelconn: "ERROR"   # Log level during connection to the board
    logleveltest: "DEBUG"   # Log level during tests
    conn_scope: "class"     # Select "function" to re-establish connection for each test or
                            # "class" if you want to reuse connection.
    always_plot: True       # Always generate comparison plots during tests
    plot_on_failure: True    # Only generate comparison plots if test fails
    delete_plots_before_run: True
    only_plot: False
    platform: "ICE-4bit-c"
    global_postscaler_min: 9
    global_postscaler_max: 26
    all_zeroes: {}
    all_ones: {}
    alternating_gain:
        min_period: 2
        max_period: 20
        step: 2
    constant_gain:
        gains: [-32768, -1, 2, 3, 32767]
    rounding:
        test_values: [-8, -1, 0, 2, 7]
    symmetric_saturation: {}
    post_rounding_saturation: {}
    zero_on_sat: {}
    offset_encoding: {}
    overflow_detection: {}
    bypass: {}
    overflow_stats:
        postscaler_min: 21
        postscaler_max: 26
        frame_cnt: [1000, 1, 50000]