connection_config:
    prog: 1                 # 0 - do not reprogram, 1 - reprogram if outdated, 2 - always reprogram
    mode: 'corr16'          # Do not change for a single board
    hwm: 'mb 498'           # For a different board change the serial number

test_config:
    loglevelconn: "ERROR"   # Log level during connection to the board
    logleveltest: "INFO"    # Log level during tests
    conn_scope: "class"     # Select "function" to re-establish connection for each test or
                            # "class" if you want to reuse connection.
