[pytest]
minversion = 7.4
log_cli = True
filterwarnings = ignore::DeprecationWarning
addopts = --maxfail=1

python_files = firmware_test.py

markers = 
    asyncio: requires asyncio to perform test
    scaler: exclusively tests scaler