[pytest]
minversion = 7.2
log_cli = True
filterwarnings = ignore::DeprecationWarning
addopts = --maxfail=1 --xreport-path="../../fw_test_results/scaler/{isodate}_{session_name}.xml"

python_files = firmware_test.py scaler_test.py

markers =
    asyncio: requires asyncio to perform test
    scaler: exclusively tests scaler
    statistical: statistical test that does not test for exact values
    complex: tests complex gains, requires firmware to be compiled with USE_COMPLEX_GAINS enabled
    floating: tests floating point gains, requires firmware to be compiled with USE_COMPLEX_GAINS disabled