[pytest]
minversion = 7.2
log_cli = True
filterwarnings = ignore::DeprecationWarning
addopts = --capture=tee-sys --xreport-config="config.yaml" --xreport-path=../../fw_test_results/test_results.xml

python_files = 
	scaler_test.py
    funcgen_test.py

markers =
    asyncio: requires asyncio to perform test
    scaler: exclusively tests scaler
    statistical: statistical test that does not test for exact values
    complex: tests complex gains, requires firmware to be compiled with USE_COMPLEX_GAINS enabled
    floating: tests floating point gains, requires firmware to be compiled with USE_COMPLEX_GAINS disabled
    
    funcgen: exclusively tests funcgen 
    funcgen_patterns: tests that captured data corresponds to injected data
    funcgen_counters: tests frame, word, and overflow counters from funcgen
    funcgen_noise_gen: tests noise generator