#!/usr/bin/env python
# Alpenhorn: announces the products of mountaineering CHIME instruments.

from ch_util import data_index as di
import h5py
import logging
import os
import peewee as pw
import psutil
import socket
import time
from watchdog.observers import Observer  
from watchdog.events import FileSystemEventHandler

# Set up logger.
logging.basicConfig(level = logging.INFO)
log = logging.getLogger("")
log.setLevel(logging.INFO)


# Parameters.
lockfile    = ".writing.lock"





# Routines for registering files, acquisitions, copies and info in the DB.
# ========================================================================

def add_acq(name, allow_new_inst=True, allow_new_atype=False, comment=None):
    """Add an aquisition to the database.
    """
    ts, inst, atype = di.parse_acq_name(name)

    # Is the acquisition already in the database?
    if di.ArchiveAcq.select(di.ArchiveAcq.id).where(
                     di.ArchiveAcq.name == name).count():
        raise di.AlreadyExists("Acquisition \"%s\" already exists in DB." %
                               name)

    # Does the instrument already exist in the database?
    try:
        inst_rec = di.ArchiveInst.get(di.ArchiveInst.name == inst)
    except pw.DoesNotExist:
        if allow_new_inst:
            di.ArchiveInst.insert(name=inst).execute()
            logging.info("Added new acquisition instrument \"%s\" to DB." %
                         inst)
        else:
            raise di.DataBaseError("Acquisition instrument \"%s\" not in DB." %
                                   inst)

    # Does the archive type already exist in the database?
    try:
        atype_rec = di.AcqType.get(di.AcqType.name == atype)
    except pw.DoesNotExist:
        if allow_new_atype:
            di.AcqType.insert(name=atype).execute()
            logging.info("Added new acquisition type \"%s\" to DB." % atype)
        else:
            raise di.DataBaseError("Acquisition type \"%s\" not in DB." % atype)

    # Giddy up!
    return di.ArchiveAcq.create(name=name, inst=inst_rec, type=atype_rec,
                                comment=comment)


def get_acqcorrinfo_keywords_from_h5(path):
  f = h5py.File(path, "r")
  n_freq = f["/"].attrs["n_freq"][0]
  n_prod = len(f["/"].attrs["chan_indices"])
  integration = f["/"].attrs["acq.udp.spf"][0] * \
                f["/"].attrs["fpga.int_period"][0]
  f.close()
  return {"integration" : integration,
          "nfreq"       : n_freq,
          "nprod"       : n_prod}


def get_filecorrinfo_keywords_from_h5(path):
  f = h5py.File(path, "r")
  start_time = f["timestamp"][0][1] + f["timestamp"][0][2] * 1e-6
  finish_time = f["timestamp"][-1][1] + f["timestamp"][-1][2] * 1e-6
  chunk_number, freq_number = di.parse_corrfile_name(os.path.basename(path))
  f.close()
  return {"start_time"   : start_time,
          "finish_time"  : finish_time,
          "chunk_number" : chunk_number,
          "freq_number"  : freq_number}


def import_file(root, acq_name, file_name):
  fullpath = "%s/%s/%s" % (root, acq_name, file_name)

  # Skip the file if ch_master.py still has a lock on it.
  if os.path.isfile("%s/%s/.%s.lock" % (root, acq_name, file_name)):
    log.debug("Skipping \"%s\", which is locked by ch_master.py." % fullpath)
    return

  # Parse the path
  try:
    ts, inst, atype = di.parse_acq_name(acq_name)
  except di.Validation:
    log.info("Skipping non-acquisition path %s." % acq_name)
    return

  # Figure out which acquisition this is; add if necessary.
  try:
    acq = di.ArchiveAcq.get(di.ArchiveAcq.name == acq_name)
    log.debug("Acquisition \"%s\" already in DB. Skipping." % acq_name)
  except pw.DoesNotExist:
    acq = add_acq(acq_name)
    log.info("Acquisition \"%s\" added to DB." % acq_name)

  # If it is a correlator acquisition, see if the info has been added.
  have_info = True
  if atype == "corr":
    if not acq.corrinfos.count():
      have_info = False

  # What kind of file do we have?
  ftype = di.detect_file_type(file_name)
  if ftype == None:
    log.info("Skipping unrecognised file \"%s/%s\"." % (acq_name, file_name))
    return

  # Make sure information about the acquisition exists in the DB.
  if atype == "corr" and ftype.name == "corr":
    if not acq.corrinfos.count():
      di.CorrAcqInfo.create(acq=acq,
                            **get_acqcorrinfo_keywords_from_h5(fullpath))
      log.info("Added information for correlator acquisition \"%s\" to " \
               "DB." % acq_name)

  # Add the file, if necessary.
  try:
    file = di.ArchiveFile.get(di.ArchiveFile.name == file_name,
                              di.ArchiveFile.acq == acq)
    log.debug("File \"%s/%s\" already in DB. Skipping." % (acq_name, file_name))
  except pw.DoesNotExist:
    md5sum = di.md5sum_file(fullpath)
    size_b = os.path.getsize(fullpath)
    file = di.ArchiveFile.create(acq=acq, type=ftype, name=file_name, 
                                 size_b=size_b, md5sum=md5sum)
    log.info("File \"%s/%s\" added to DB." % (acq_name, file_name))

  # Register the copy of the file here on the collection server, if (1) it does
  # not exist, or (2) it does exist but has been labelled as corrupt. If (2),
  # check again.
  if not file.copies.where(di.ArchiveFileCopy.node == node).count():
    copy = di.ArchiveFileCopy.create(file=file, node=node, has_file='Y',
                                     wants_file = False)
    log.info("Registered file copy \"%s/%s\" do DB." % (acq_name, file_name))

  # Make sure information about the file exists in the DB.
  if ftype.name == "corr":
    # Add if (1) there is no corrinfo or (2) the corrinfo is missing.
    if not file.corrinfos.count():
      do_add = True
    elif not file.corrinfos[0].start_time:
      do_add = True
    else:
      do_add = False

    if do_add:
      try:
        di.CorrFileInfo.create(file=file,
                               **get_filecorrinfo_keywords_from_h5(fullpath))
        log.info("Added information for file \"%s/%s\" to DB." %
                 (acq_name, file_name))
      except ValueError:
        if not file.corrinfos.count():
          di.CorrFileInfo.create(file=file)
        log.warning("Missing info for file \"%s/%s\": HDF5 datasets " \
                      "empty. Leaving fields NULL." % (acq_name, file_name))


def update_node(node):
  # Make sure this node is usable.
  if not node.mounted:
    log.debug("Skipping unmounted node \"%s\"." % node.name)
    return
  if node.suspect:
    log.debug("Skipping suspected node \"%s\"." % node.name)

  # Check for copy requests.
  for req in di.ArchiveFileCopyRequests.select().where(
                di.ArchiveFileCopyRequests.completed == False and
                di.ArchiveFileCopyRequests.group_to == node.group):
    print req



# Watchdog stuff
# ==============

class register(FileSystemEventHandler):
  def __init__(self, root):
    self.root = root
    if self.root[-1] == "/":
      self.root = self.root[0:-1]
    super(register, self).__init__()

  def on_modified(self, event):
    # Figure out the parts; it should be ROOT/ACQ_NAME/FILE_NAME
    subpath = event.src_path.replace(self.root + "/", "").split("/")
    if len(subpath) == 2:
      import_file(self.root, subpath[0], subpath[1])
    return

  def on_deleted(self, event):
    # For lockfiles: ensure that the file that was locked is added: it is
    # possible that the watchdog notices that a file has been closed before the
    # lockfile is deleted.
    subpath = event.src_path.replace(self.root + "/", "").split("/")
    if len(subpath) == 2:
      if subpath[1][0] == "." and subpath[1][-5:] == ".lock":
        subpath[1] = subpath[1][1:-5]
        import_file(self.root, subpath[0], subpath[1])





# Main Street
# ===========

if __name__ == "__main__":
  # Get the nodes mounted on this host.
  host = socket.gethostname()
  node_list = []
  for node in di.StorageNode.select().where(di.StorageNode.host == host and
                                            di.StorageNode.mounted):
    node_list.append(node)

  # Get the node.
  if not len(node_list):
    raise Exception("No nodes on this host (\"%s\") registered in the DB!" % 
                    host)

  # If any node has auto_import set, look for new files and add them to the
  # DB. Then set up a watchdog for it.
  obs_list = []
  for node in node_list:
    if node.auto_import:
      log.info("Crawling base directory \"%s\" for new files." % node.root)
      for acq_name, d, f_list in os.walk(node.root):
        for file_name in sorted(f_list):
          import_file(node.root, os.path.basename(acq_name), file_name)
      obs_list.append(Observer())
      obs_list[-1].schedule(register(node.root), node.root, recursive = True)
    else:
      obs_list.append(None)

  # Caveat canem!
  for obs in obs_list:
    if obs:
      obs.start()

  try:
    while True:
      time.sleep(1)
  except KeyboardInterrupt:
    for obs in obs_list:
      if obs:
        obs.stop()

for obs in obs_list:
  if obs:
    obs.join()
