#!/usr/bin/env python
# Alpenhorn: announce datafile information to the database

from ch_util import data_index as di
import datetime
import optparse
import peewee as pw
from sets import Set
import sys

def ask_yesno(question):
  answer = raw_input("%s [Y/N] " % question)
  if answer == "y" or answer == "Y":
    return True
  else:
    return False


def node2group(node_name, group_name, force=False, nice=0):
  try:
    from_node = di.StorageNode.get(name=node_name)
  except pw.DoesNotExist:
    raise Exception("Node \"%s\" does not exist in the DB." % node_name)
  try:
    to_group = di.StorageGroup.get(name=group_name)
  except pw.DoesNotExist:
    raise Exception("Group \"%s\" does not exist in the DB." % group_name)

  to_copy = Set()
  for to_node in di.StorageNode.select().where(di.StorageNode.group ==
                                               to_group):
    to_copy |= Set(di.ArchiveFileCopy.select().where(
                      di.ArchiveFileCopy.node == to_node and
                      di.ArchiveFileCopy.has_file == 'Y'))

  from_copy = Set(di.ArchiveFileCopy.select().where(
                     di.ArchiveFileCopy.node == from_node and
                     di.ArchiveFileCopy.has_file == 'Y'))

  copy = from_copy - to_copy
  if not len(copy):
    print "No files to copy."
    return

  print "Will request that %d files be copied from node %s to group %s." % \
        (len(copy), node_name, group_name)
  if not (force or ask_yesno("Do you want to proceed?")):
    print "Aborted."
    return

  sys.stdout.write("Updating DB ")
  for c in copy:
    try:
      req = di.ArchiveFileCopyRequest.get(file=c.file, group_to=to_group,
                                          node_from=from_node)
      di.ArchiveFileCopyRequest.update(nice=nice, completed=False, 
         n_requests=req.n_requests + 1, 
         timestamp=datetime.datetime.now()).where(
           di.ArchiveFileCopyRequest.file == c.file).where(
           di.ArchiveFileCopyRequest.group_to == to_group).where(
           di.ArchiveFileCopyRequest.node_from == from_node).execute()
    except pw.DoesNotExist:
      
      di.ArchiveFileCopyRequest.create(file=c.file, group_to=to_group,
                                       node_from=from_node, nice=nice,
                                       completed=False, n_requests = 1,
                                       timestamp=datetime.datetime.now())
    sys.stdout.write(".")
    sys.stdout.flush()
  sys.stdout.write("\n")



def usage():
  print "Usage!"
  exit(0)

if __name__ == "__main__":
  parser = optparse.OptionParser()
  parser.add_option( "-n", "--nice", dest="nice" )
  parser.add_option( "-f", "--force", dest="force" )
  parser.set_defaults(nice=0, force=False)

  option, arg = parser.parse_args()

  if not len(arg):
    usage()

  cmd = arg[0]

  if cmd == "node2group":
    if len(arg) != 3:
      usage()
    node2group(arg[1], arg[2], force=option.force, nice=option.nice)
