#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  pull-requests:
    '**':
      - step:
          name: Automatic test
          # Test which require no configuaration of hardware components and are therefore platform agnostic
          caches:
            - pip
          script:
            - if [ -f pyproject.toml ]; then pip install -e .; fi
            - pip install pylint
            - pylint pychfpga/ --errors-only

