#Pull request pipeline
#Validation of pull requests into the main deployment branch

image: python:3.8

pipelines:
  pull-requests:
    '**':
      - step:
          name: Automatic static code analysis
          # Test which require no configuaration of hardware components and are therefore platform agnostic
          # This test will ensure that none of the modifications made into the deploy branch cause any disturbances to other elements of the project
          caches:
            - pip
          script:
            - if [ -f pyproject.toml ]; then pip install -e .; fi
            - pip install pylint
            #the errors only tags limits the scope of the linter to purely functional errors and ignores style concerns
            - pylint pychfpga/ --errors-only
  branches:
    '{master,develop,jfc/dev}':
      - step:
          caches:
            - pip
          script: # Modify the commands below to build your repository.
            - DOC_REPO='winterlandcosmology.bitbucket.io'
            - DOC_REPO_URL='git@bitbucket.org:winterlandcosmology/'$DOC_REPO'.git'
            - DOC_SPHINX_ROOT_FOLDER='docs'
            - DOC_BUILD_FOLDER='build'
            - DOC_PUBLISH_FOLDER='pychfpga/'$BITBUCKET_BRANCH
            - pip install -e .[docs]
            - cd $DOC_SPHINX_ROOT_FOLDER
            - echo 'Building for '$BITBUCKET_REPO_SLUG/$BITBUCKET_BRANCH
            - make html
            - cd $DOC_BUILD_FOLDER
            - git clone $DOC_REPO_URL
            - rm -rf $DOC_REPO/$DOC_PUBLISH_FOLDER/*
            - mkdir -p $DOC_REPO/$DOC_PUBLISH_FOLDER
            - cp -r html/* $DOC_REPO/$DOC_PUBLISH_FOLDER/
            - cd $DOC_REPO
            - git config --global user.email "bb-pipelines@jfcliche.com"
            - git config --global user.name "BitBucket Pipelines ($BITBUCKET_REPO_SLUG/$BITBUCKET_BRANCH)"
            - git add --all $DOC_PUBLISH_FOLDER
            - git diff-index --quiet HEAD -- || git commit -a -m "bitbucket-pipelines updated $BITBUCKET_BRANCH branch into $DOC_PUBLISH_FOLDER sphinx-generated documentation"
            - git push


