description "CHIME Master Control"
author  "CHIME Collaboration of Awesome People"

#start on runlevel [234]
stop on runlevel [0156]

exec /usr/sbin/ch_master.py -c /etc/CHIME/ch_master.conf \
                            -s /etc/CHIME/ch_master.spec
