# Configuration for ch_master_raw_adc.py. Only edit this file if you know what you are
# doing!

#History:
#2015-10-13 JM: First version.

#===============================================================================
#===============================================================================
#==   GLOBAL SETTINGS
#===============================================================================
#===============================================================================

log_target = ch_master_raw_time_debug.log # Logging target ('stream', 'syslog' or a filename)
log_level = debug # Logging level ('info', 'debug', 'warn', 'error')

#===============================================================================
#===============================================================================
#==    FPGA SETTINGS
#===============================================================================
#===============================================================================

[fpga]
  yamlfile = pychfpga/yaml_iceboard_list.txt # Yaml file with list of boards and respective IP addresses and handlers
  subarrays = 2 # Keep in the hardware map only the boards that are in the specified subarrays. Use 2 at DRAO
  prog = 1 #Program the FPGA. prog=0 programs only if not already programmed. prog=1 forces the FPGA programming 
  bitfile = ../chfpga/xilinx_projects/CHFPGA_MGK7MB_REV2/CHFPGA_MGK7MB_REV2.runs/impl_Rev2/chFPGA_MGK7MB_Rev2.bit 
  # bitfile used to to program the FPGAs
  no_mezz = 0 # Do not attempt to auto-detect the mezzanines
  open = 1 # Opens communication with the FPGAs, open=0 skips the firmware initialization phase
  sampling_frequency = 800       # Sampling frequency of the ADC in MHz
  data_width = 4       # Data width of each Re and Im component of the channelizer output. Can be 4 or 8
  group_frames = 4     # Number of frames to group before sending to the GPU or FPGA correlator.
  delay_file = pychfpga/delays_aug_2015.pkl # File containing ADC delays for all boards
  sync_method = distributed_time # Syncing method (distributed_time, centralized_time_trigger, centralized_soft_trigger, local_soft_trigger)
  sync_source = bp_time # Syncing source (bp_gpio_int, bp_time', bp_trig)
  adc_channels = 0,3,5,2,6,15,10,11 # List of ADC channels to select in 8 bit raw mode (order matters!)
