---
version: '3.8'
# x-env:
#     - &_pychfpga_image wtlpychfpga/pychfpga:2020.06-rc1-654-gde161d07
#     - &_data_folder "/data"
#     - &_config_file "../ch_config/mcgill_config.yaml"
#     - &_config_name "mcgill"

# networks:
#     pychfpga_network:

# volumes: # value is a {volume_name:host_path, ...} dictionary
#     data:  # stores run data in a named volume on the host

configs:
  fpga_config:
    file: ${PYCHFPGA_CONFIG_FILE}

services:

    build: # this is used to build the image locally only. No service is started.
        image: ${PYCHFPGA_IMAGE}
        build:
          context: .
          dockerfile: Dockerfile
          target: deploy
          # args:
          #   github_ssh_key: $SSH_AUTH_SOCK


    fpga_master:
        image: ${PYCHFPGA_IMAGE}
        volumes: # elements are expressed as a list of strings, each in the format "volume_name:container_path"
            - "${PYCHFPGA_DATA_FOLDER}:/data"  #

        configs:
            - source: fpga_config
              target: /config/fpga_config.yaml

        command: ["fpga_master", "/config/fpga_config.yaml:${PYCHFPGA_CONFIG_NAME}"]
        network_mode: "host"
        # ports:
        #   - "54321:54321"
        deploy:
          mode: replicated
          replicas: 1
          resources:
            reservations:
              cpus: "0.5"
              memory: "256M"
            limits:
              cpus: "1"
              memory: "2gb"
        environment:
          - PYTHONUNBUFFERED=1
    # raw_acq:
    #     image: *_pychfpga_image
    #     volumes:
    #         - data:/data
    #     command: ["chime_raw_acq"]
    #     network_mode: "host"
    #     # ports:
    #     #   - "54322:54322"
    #     #   - "54326:54326/udp"
    #     deploy:
    #         mode: replicated
    #         replicas: 1
    #         resources:
    #             reservations:
    #               cpus: "1"
    #               memory: "256M"
    #             limits:
    #               cpus: "2"
    #               memory: "2gb"
    #     environment:
    #       - PYTHONUNBUFFERED=1
    # ps:
    #     image: *_pychfpga_image
    #     volumes:
    #         - config:/config
    #         - data:/data
    #     command: ["chime_rx_ps", *_container_config_path_name_ ]
    #     ports:
    #       - "54324:54324"
    #     deploy:
    #       mode: replicated
    #       replicas: 1
    #       resources:
    #         reservations:
    #           cpus: "0.5"
    #           memory: "256M"
    #         limits:
    #           cpus: "1"
    #           memory: "2gb"
    #     environment:
    #       - PYTHONUNBUFFERED=1
    # gps:
    #     image: *_pychfpga_image
    #     volumes:
    #         - data:/data
    #         - config:/config
    #     # command: ["ls", "/data/config"]
    #     command: ["chime_gps", *_container_config_path_name_ ]
    #     ports:
    #       - "54325:54325"
    #     deploy:
    #       mode: replicated
    #       replicas: 1
    #       resources:
    #         reservations:
    #           cpus: "0.5"
    #           memory: "256M"
    #         limits:
    #           cpus: "1"
    #           memory: "2gb"
    #     environment:
    #       - PYTHONUNBUFFERED=1
