# Configuretion file for the make_sphinx_docs.sh script
# Each line list how to build a separate set of Sphinx documentation in this repo
# All paths are relative to the repo root folder
#   make_folder: Folder from which to run 'make html'
#   source_folder: Folder where we fond the build results
#   target_folder: folder where we move the build results, under www/repo_name/branch_name/

make_folder=/pychfpga/docs, source_folder=/pychfpga/docs/_build/html, target_folder=pychfpga
make_folder=/doc, source_folder=/doc/build/html, target_folder=ch_acq
