#!/usr/bin/env python
#
# masterctl: control and query ch_master via the REST interface.
#

from __future__ import print_function

import click
import sys
from ch_master_client import ChMasterClient


# Command line interface

@click.group(context_settings=dict(help_option_names=['-h','--help']))
@click.option('--host', default='localhost', help="ch_master host.")
@click.option('--port', default=54321, help="ch_master port.", type=int)
@click.pass_context
def cli(ctx, host, port):
    """
    ch_master command line interface.

    This is called whenever the program is launched, and creates a CHMasterClient onject instance
    which is stored in the context object for future use by commands.
    """

    # Hook print functions to provide nicer command line output
    class ClickChMasterClient(ChMasterClient):
        def print(self, msg):
            click.echo(msg)
        def print_error(self, msg):
            click.secho(msg, bold=True, fg='red')
        def error(self, msg):
            self.print_error(msg)
            sys.exit(-1)

    # store CHMaster client object in context object so it can be used by CLI commands
    ctx.obj = ClickChMasterClient(host, port)


def add_command(cli, name, args=[], help=None):
    """ Add a command that will call the corresponding method in the CHMasterClient instance"""

    # Get command line description from method docstring if not specified
    if help is None:
        help = getattr(CHMasterClient,name).__doc__.strip()

    @cli.command(name, short_help=help)
    @click.pass_context
    def cmd(ctx, *args, **kwargs):
        getattr(ctx.obj, name)(*args, **kwargs)   # call method 'name' of CHMasterClient instance

    # Add arguments, if any
    for a in args:
        click.option(*a)(cmd)

add_command(cli, 'ping')
add_command(cli, 'start', args=[('--yaml','-y')])
add_command(cli, 'status')
add_command(cli, 'stop')
add_command(cli, 'switch_gains')
add_command(cli, 'kotekan_start', args=[('--yaml','-y')])


@cli.command()
@click.pass_obj
def nop(obj):
    """ Do nothing """
    print('Doing nothing with ', obj)



if __name__ == '__main__':
    try:
        cli()
    except:
        pass
    print('done')
    w=3
    m = click.get_current_context().obj  # get CHMasterClient object instance for use in interctive python sessions
