#!/usr/bin/python

"""
REFCLK.py module 
 Implements FMC Reference clock interface
#
# History:
	2011-09-22 JFC: Created
	2011-09-25 JFC: Modified to support new method on incrementing phase (pulse PS_EN unstead of PS_CLK) 
	2011-11-15 JFC: Lots of modifications done to debug SYNC clock alignment. 
"""

from Module import Module_base, BitField

import time
import numpy as np

class REFCLK_base(Module_base):


	CONTROL=BitField.CONTROL
	STATUS=BitField.STATUS
	DRP=BitField.DRP

	BITS={
		'PS_CLK' : 		BitField(CONTROL,0x00,0,doc='Phase shift control clock -- Not used'),
		'PS_EN':		BitField(CONTROL,0x00,1,doc='Enable Phase shift increment/decrement when transitionning from 0 to 1'),
		'PS_INCDEC':	BitField(CONTROL,0x00,2,doc='1=Increment phase by 1/56th of cycle, 0= decrement phase by same amount'),
		'MASTER':		BitField(CONTROL,0x00,3,doc='1=board is MASTER: SYNC SMA is an output, 0= board is SLAVE: SYNC SMA is an input'),
		'ENCODE_SYNC':	BitField(CONTROL,0x00,4,doc='Generate a SYNC signal encoded on the 10 MHz clock output'),
		'SMA_SYNC':		BitField(CONTROL,0x00,5,doc='Generate a SYNC signal on the SMA connector (MASTER mode only). The SYNC is synchronized to the 10 MHz output (transitions on its falling edge)'),
		'DCI_RESET':	BitField(CONTROL,0x00,6,doc='Resets the DCI'),
		'SYNC':			BitField(CONTROL,0x00,7,doc='Force a SYNC to the ADC, synchronized on the FMC Reference clock'),

		'SYNC_DELAY':	BitField(CONTROL,0x01,0,5,doc='Delay between the FMC Reference clock and the SYNC edge (0-31). Must pulse SYNC_DELAY_RST to load.'),
		'MMCM_RST':	BitField(CONTROL,0x01,6,doc='Resets the MMCM. Must be held high while the DRP port is used.'),
		'SYNC_DELAY_RST':	BitField(CONTROL,0x01,7,doc='Resets the SYNC line IODELAY and loads the delay value specified in SYNC_DELAY.'),

		'REFCLK_DELAY_RST':	BitField(CONTROL,0x02,7,doc='Resets the REFCLK line IODELAY and loads the delay value specified in REFCLK_DELAY.'),
		'REFCLK_DELAY':		BitField(CONTROL,0x02,0,5,doc='Delay applied to the FMC Reference clock within the FPGA (0-31). Must pulse REFCLK_DELAY_RST to load.'),

		'PS_DONE' : 	BitField(STATUS,0x080+ 0x00,0,doc='Phase shift completed'),
		'LOCKED' : 		BitField(STATUS,0x080+ 0x00,1,doc='MCMM is locked'),
		'RECOVERED_SYNC':	BitField(STATUS,0x080+ 0x00,2,doc='1 when a SYNC signal encoded on the 10 MHz is detected '),
		'DCI_LOCKED':	BitField(STATUS,0x080+ 0x00,3,doc='1 when DCI is locked'),
		'DIFF_COUNTER':	BitField(STATUS,0x080+ 0x01,0,8,doc='DIfference between clocks'),

		'SYNC_DELAY_READBACK':	BitField(STATUS,0x080+ 0x02,0,5,doc='Reads back the delay set onthe SYNC IODELAY'),
		'ADC_CLK_SAMPLE':	BitField(STATUS,0x080+ 0x02,7,doc='ADC_CLK sampled on the 200 MHZ generated by the MCMM from the 10 MHz FMC Reference clock'),
		# MMCM registers
		'MMCM_FB_LOW' : 		BitField(DRP,0x14,0,6,doc='MCMM Feedback clock Low time (in VCO cycles)'),
		'MMCM_FB_HIGH' : 		BitField(DRP,0x14,6,6,doc='MCMM Feedback clock High time (in VCO cycles)'),
		'MMCM_FB_PHASE' : 		BitField(DRP,0x14,13,3,doc='MCMM Feedback clock phase in increments of 1/8 the VCO period'),

		'MMCM_REFCLK200_LOW' : 	BitField(DRP,0x0A,0,6,doc='MCMM FMC 200 MHz reference clock Low time (in VCO cycles)'),
		'MMCM_REFCLK200_HIGH': 	BitField(DRP,0x0A,6,6,doc='MCMM FMC 200 MHz clock High time (in VCO cycles)'),
		'MMCM_REFCLK200_PHASE':	BitField(DRP,0x0A,13,3,doc='MCMM FMC 200 MHz clock phase in increments of 1/8 the VCO period'),
		'MMCM_REFCLK200_DELAY':	BitField(DRP,0x0B,0,6,doc='MCMM FMC 200 MHz clock delay in increments of the VCO period'),

		'MMCM_POWER':	BitField(DRP,0x28,0,16,doc='MCMM Power bits. Must be set to 0xFFFF in order to successfully program the other MMCM registers'),

	}


	def __init__(self,fpga):
		super(self.__class__,self).__init__(fpga,fpga.SYSTEM_PORT, fpga.SYSTEM_REFCLK_MODULE)

	def init(self):
		self.set_refclk_delay(0)

	def sync(self, delay=None):
		if delay is not None:
			self.set_sync_delay(delay)
		self.set_refclk_delay(0)
		self.pulse_bit('ENCODE_SYNC')

	def inc_phase(self,inc_amount):
		if inc_amount>0:
			self.PS_INCDEC=1
		else:
			self.PS_INCDEC=0
		for i in range(abs(inc_amount)):
			self.pulse_bit('PS_EN')
			#while not self.PS_DONE: pass

	def set_sync_delay(self,delay):
		"""
		Sets the delay on the SYNC line. Valid range is 0-31.
		"""
		self.SYNC_DELAY=delay
		self.pulse_bit('SYNC_DELAY_RST')

	def set_refclk200_phase(self,phase):
		"""
		Sets DIVCLK phase on MCMM in inrements of 1/8 VCO cycles. Valid range is 0-512.
		"""
		self.MMCM_RST=1
		self.MMCM_POWER=0xFFFF
		self.MMCM_REFCLK200_PHASE=phase & 0x07
		self.MMCM_REFCLK200_DELAY=phase>>3
		self.MMCM_RST=0


	def scan_refclk200_phase(self,sleep=0.3):
		samples=[];
		for phase in range(24): # FB=60, DIVOUT=3. Cycle = 8* DIVOUT
			self.set_refclk200_phase(phase)
			time.sleep(sleep)
			samples.append(self.ADC_CLK_SAMPLE)
		print ''.join(('0','1')[sample] for sample in samples)
		#return samples

	def set_refclk_delay(self,delay):
		"""
		Sets the delay in the Reference clock received into the FPGA. Valid range is 0-31.
		"""
		self.REFCLK_DELAY=delay
		self.pulse_bit('REFCLK_DELAY_RST')

	def scan_refclk_delay(self,sleep=0.005):
		samples=[];
		for delay in range(32): 
			self.set_refclk_delay(delay)
			time.sleep(sleep)
			samples.append(self.ADC_CLK_SAMPLE)
		self.set_refclk_delay(0)
		return samples

	def print_bit_vector(self,samples):
		print ''.join(('0','1')[sample] for sample in samples)

	def scan_sync_delay(self,sleep=0.005):
		samples=[];
		for scan_delay in range(32): 
			print 'Delay %2i:' % scan_delay,
			self.sync(scan_delay)
			s=self.scan_refclk_delay(sleep=sleep)
			self.print_bit_vector(s)
		#print ''.join(('0','1')[sample] for sample in samples)

	def status(self):
		print '---------------------FMC REF CLK  ------------------------------------'
		print 'MCMM Locked: %i' % (self.LOCKED)
		print '----------------------------------------------------------------------'


