# Notes:
#     - Semicolumns must be followed by a space
#     - Floats must have a decimal point *AND* an exponent sign if an exponent is used (i.e. 10.0 and 10.e+3 is valid, 10e3, 10.e3, 10e+3 are all invalid)
aliases:
comment: |
    This is a long note

    That extends many lines
        this is indented more

test_results_folder: './test_results'
mgadc08_model_number: ['MGADC08']
xformat: ['pdf','rst']  # Output formats for the test reports. xml is always saved.

# DEBUGGING options
debug:
    default_model: 'MGADC08'
    default_serial: None
    no_date: True


instruments:
    dmm:       {labpy_object: 'agilent_dmm', interface: 'prologix_eth', ip_addr: '10.10.10.137', gpib_addr: 22} # Agilent 34410A multimeter (we don't use the LAN connection so we can go back in local mode remotely)
    ps12v:     {labpy_object: 'AgilentPS',   interface: 'prologix_eth', ip_addr: '10.10.10.137', gpib_addr: 5}  # Agilent E3648A dual output power supply  12V on output 1, output 2 not used
    ps3v3_2v5: {labpy_object: 'AgilentPS',   interface: 'prologix_eth', ip_addr: '10.10.10.137', gpib_addr: 6}  # Agilent E3648A dual output power supply. 3.3V on output1, 2.5V on output 2
    na:        {labpy_object: 'hp8753e',     interface: 'prologix_eth', ip_addr: '10.10.10.137', gpib_addr: 14} # HP8753E Network Analyzer

?: &default_fpga_array
    iceboards: 49
    mdns_delay: 1


test_list:
    # This list all the tests that will be done my the test software, in the proper order
    # path is the argument given to nose to find the test fucntion, in the form of module_path:function or module_path:class.method
    # This path is also the path used by XReport to identify tests results, with the exception that the semicolon ':' is replaced by a dot '.'
    - [ 'imp', {description: 'Impedance test (needs S/N)',   path: 'mgadc08_bench_tests:MGADC08BenchTests.impedance_test', required: yes, require_serial_number: yes, dependencies: null}]
    - [ 'smk', {description: 'Power up test (needs S/N)',    path: 'mgadc08_bench_tests:MGADC08BenchTests.smoke_test',     required: yes, require_serial_number: yes, dependencies: imp}]
    - [ 'eep', {description: 'EEPROM Programming and test (needs S/N)',  path: 'mgadc08_bench_tests:MGADC08CarrierTests.eeprom_test',  required: yes, require_serial_number: yes, dependencies: smk}]
    - [ 'pow', {description: 'Carrier power test',           path: 'mgadc08_bench_tests:MGADC08CarrierTests.power_test',   required: yes, require_serial_number: no, dependencies: smk}]
    - [ 'spi', {description: 'SPI & PLL test',               path: 'mgadc08_bench_tests:MGADC08CarrierTests.spi_pll_test', required: yes, require_serial_number: no, dependencies: smk}]
    - [ 'rmp', {description: 'Ramp test',                    path: 'mgadc08_bench_tests:MGADC08CarrierTests.ramp_test',    required: yes, require_serial_number: no, dependencies: smk}]
    - [ 's11', {description: 'S11 test',                     path: 'mgadc08_bench_tests:MGADC08CarrierTests.s11_test',     required: yes, require_serial_number: no, dependencies: smk}]


menu:
    # The menu item will match the user input to either the 'key' field or to the regular expression 'regex'. The matching dictionary is returned.
    # If a regular expression is given, string parameters are replaced by string_param.format(regex_matched_group_list), i.e. '{0}' is replaced by the first matched group etc. The 'key' and 'regex' fields are excluded from this conversion.
    # Entry types are:
    #  test: a test to run. test_tag refers to the test to run in test_list (defined above). A regex entry will be added to match the tets tag and tets path. The description will be taken from the test description if none is provided here.
    #  exit: exit the menu
    #  text: do nothing. The description is shown in the menu if there is one.
    #  board_info: Sets the current board model and serial number. The serial number can be extracted from string parsed by the regex
    #
    - { key: '1', type: test, test_tag: imp}
    - { key: '2', type: test, test_tag: smk}
    - { key: '3', type: test, test_tag: eep}
    - { key: '4', type: test, test_tag: pow}
    - { key: '5', type: test, test_tag: spi}
    - { key: '6', type: test, test_tag: rmp}
    - { key: '7', type: test, test_tag: s11}

    - { key: 'Q', description: 'Exit',                                                type: exit}
    - {           description: "or Enter or scan board's serial number or menu item", type: text}
    - { regex: '29821-0000-(\d{4})',                                                  type: board_info, model: 'MGADC08', serial: '{0}', next_key: '1'}  # 29821-000-nnnn are MGADC08 Serial nnnn
    - { regex: '35896-0000-(\d{4})',                                                  type: board_info, model: 'MGADC08', serial: '{0}', next_key: '1'}  # 29821-000-nnnn are MGADC08 Serial nnnn
    - { regex: '(0\d{3})',                                                            type: board_info, model: 'MGADC08', serial: '{0}', next_key: '1'}  # 0nnn are MGADC08 Serial nnnn


##################################
# Test-specific parameters
##################################

bench_tests:
    setup:
        instruments: [dmm, ps12v, ps3v3_2v5] # Subset of instruments we use in the bench tests
        rails:  # ps: name if the power supply, as in the instruments list above
            vcc12v: {ps: 'ps12v',     output: 1, voltage: 12, current_limit: 0.200} # ps12v, Output 1
            unused: {ps: 'ps12v',     output: 2, voltage: 0,  current_limit: 0.010} # ps12v, Output 2
            vcc3v3: {ps: 'ps3v3_2v5', output: 1, voltage: 3.3, current_limit: 2.800} # ps3v3_2v5, Output 1
            vcc2v5: {ps: 'ps3v3_2v5', output: 2, voltage: 2.5, current_limit: 1.000} # ps3v3_2v5, Output 2

    impedance:
        max_impedance: 1.0e+10  # any measurement more than this is probably not taken correctly
        test_points:
        # delay: delay to wait before taking the measurement
        # zmin: minimum impedance below which the test will fail
           - ['J7-2 (12V)',     {delay: 0.1, zmin: 500}]
           - ['J7-3 (2.5V)',    {delay: 0.1, zmin: 500}]
           - ['J7-4 (3.3V)',    {delay: 0.1, zmin: 500}]
           - ['3V3 test point', {delay: 0.1, zmin: 500}]
           - ['1V8 test point', {delay: 0.1, zmin: 500}]

    smoke_test:
        rails:
            vcc12v: {vmin: 11.9, vmax: 12.1, imin: 0.010, imax: 0.100} # ps12v, Output 1
            vcc3v3: {vmin: 3.2,  vmax: 3.4,  imin: 2.400, imax: 2.800} # ps3v3_2v5, Output 1
            vcc2v5: {vmin: 2.4,  vmax: 2.6,  imin: 0.090, imax: 0.120} # ps3v3_2v5, Output 2

        min_test_voltage: 0.1   # voltage below which we ask the user to try again a voltage measurmenet

        test_points:
           - ['3V3 test point', {vmin: 3.20, vmax: 3.40}]  # We use a list to preserve the order of the items presentd to the operator
           - ['1V8 test point', {vmin: 1.7, vmax: 1.9}]

carrier_tests:
    setup:
        fmc_slot: 1 # This is the FMC slot where we expect the Mezzanine to be

    eeprom_test:
        instruments: [dmm] # Subset of instruments we use in these tests
        fpga_array: {<<: *default_fpga_array, no_mezz: True, prog: 1,  open: 1}
        revision_table:
            2: {sn_min: 0, sn_max: 42}
            3: {sn_min: 43, sn_max: 1000}
        overwrite: false  # true, false, ask

    power_test:
        # instruments: [dmm] # Subset of instruments we use in these tests
        fpga_array: {<<: *default_fpga_array, no_mezz: 1, prog: 1,  open: 1}

        pow_stab_time: 0.5  # Tibe to wait after board power on and voltage measurmeents
        rails:
            vcc12v: {vmin: 11.9, vmax: 12.2, imin: 0.010, imax: 0.120} #
            vcc3v3: {vmin: 3.2,  vmax: 3.4,  imin: 2.400, imax: 2.800} #
            vadj:   {vmin: 2.4,  vmax: 2.6,  imin: 0.090, imax: 0.120} #

    spi_pll_test:
        # instruments: [dmm] # Subset of instruments we use in these tests
        fpga_array: {<<: *default_fpga_array, no_mezz: 1, prog: 1,  open: 1}

        pcb_temp: {tmin: 10, tmax: 60, iterations: 10}
        adc_temp: {tmin: 10, tmax: 85, iterations: 10}
        valid_adc_chip_id: [0x0119]
        blink_delay: 0.2  # Time between LED blinks

        pll_iterations: 2
        pll_gate_time: 0.1
        pll_frequencies: [800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000]  # Frequencies in MHz, range is
        pll_freq_err_max: 0.000001 # in MHz. We have a gate time of 0.01s, err =

        test_mgt_pll: false  # This test does not always work yet.
        pll2_iterations: 2
        pll2_gate_time: 0.1
        pll2_frequencies: [10, 20, 50, 100, 125, 156.25, 200, 250, 312.5, 400, 600]  # Frequencies in MHz, range is 5 to 1000 MHz
        pll2_freq_err_max: 0.000001 # in MHz. We have a gate time of 0.01s, resolution = 160 Hz

    ramp_test:
        # instruments: [dmm] # Subset of instruments we use in these tests
        fpga_array: {<<: *default_fpga_array, no_mezz: 1, prog: 1,  open: 1}

    s11_test:
        instruments: [na] # Subset of instruments we use in these tests
        fpga_array: {<<: *default_fpga_array, no_mezz: 1, prog: 1,  open: 1}
        s11_max : -15 # in dB
        adc_trim_value: 15  # 0-15, default is 8. Applies to all channels.
        freqs: [17, 27, 37, 47, 57, 67, 81, 93, 107, 153, 207, 253, 307, 353, 407, 507, 553, 607, 653, 707, 753, 807, 853, 907, 953, 1007, 1023, 1047, 1065, 1107, 1123, 1147, 1165, 1207]  # MHz
        power_level: -6 # dBm
        expected_frequency_response: [[200, -3], [900, -6]]