#!/bin/sh

DAEMON=/usr/bin/iceboard-monitor.py
DAEMON_USER=root
PIDFILE=/var/run/$DAEMON_NAME.pid

do_start () {
   start-stop-daemon -b -p $PIDFILE -m \
       -u $DAEMON_USER -c $DAEMON_USER \
       -x $DAEMON -S -- $DAEMON_OPTS
}

do_stop () {
   start-stop-daemon -p $PIDFILE -u root -c root -K
}

case "$1" in

    start)
        do_start
        ;;

    stop)
        do_stop
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        start-stop-daemon -p $PIDFILE -t -K &> /dev/null && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
