#!/bin/sh

start() {
        echo -n "Setting RMEM_MAX..."
	/sbin/sysctl -qw net.core.rmem_max=16777216
        echo "OK"
}
stop() {
	:
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
