ready_check: 0 #If this is set to 0, the tests can be strung together without lots of prompting
#For example:
#Tests 3-4 : Require backplane + PLL programmer in place
#Tests 5-8 : Requires backplane + ARM Ethernet + Flashcard + RS232 cable
#Test 9: solo test
#Test 10: solo test
#Test 11-14 : Requires backplane + ARM Ethernet + Flashcard + SPF(FPGA ethernet) + Heatsink + QSFP cable + Mezzanines (PLL programmer and RS232 cable can be left in place)

# Notes:
#     - Semicolumns must be followed by a space
#     - Floats must have a decimal point *AND* an exponent sign if an exponent is used (i.e. 10.0 and 10.e+3 is valid, 10e3, 10.e3, 10e+3 are all invalid)
aliases:
comment: |
    This is a long note

    That extends many lines
        this is indented more

# test_results_folder: './test_results'
#test_results_folder: '../test_results/motherboard_qc'
test_results_folder: '../../test_data'
fpga_bit_file: '../../../chfpgalite/xilinx_projects/CHFPGA_MGK7MB_REV2/CHFPGA_MGK7MB_REV2.runs/impl_Rev2/chFPGA_MGK7MB_Rev2.bit'
model_number: 'MGK7MB'
xformat: ['pdf']  # Output formats for the test reports. xml is always saved.

default_model: 'MGK7MB'
default_serial: '0342'

#For changing prologix address, use ./nfcli --list to find devices
instruments:
    dmm:       {labpy_object: 'agilent_dmm', interface: 'lan', ip_addr: '11.11.11.45', gpib_addr: 22} # Agilent 34410A multimeter (we don't use the LAN connection so we can go back in local mode remotely)
    ps18v:     {labpy_object: 'agilent_N5700', interface: 'lan', ip_addr: '11.11.11.73', gpib_addr: 5}  # Agilent N5764A power supply
#   ps3v3_2v5: {labpy_object: 'AgilentPS',   interface: 'prologix_eth', ip_addr: '10.11.1.132', gpib_addr: 6}  # Agilent E3648A dual output power supply. 3.3V on output1, 2.5V on output 2
#   na:        {labpy_object: 'hp8753e',     interface: 'prologix_eth', ip_addr: '10.11.1.132', gpib_addr: 14} # HP8753E Network Analyzer


?: &default_fpga_array
    iceboards: 342
    mdns_delay: 1


test_list:
    # This list all the tests that will be done by the test software, in the proper order
    # path is the argument given to nose to find the test fucntion, in the form of module_path:function or module_path:class.method
    # This path is also the path used by XReport to identify tests results, with the exception that the semicolon ':' is replaced by a dot '.'
    insp:  {description: 'Inspection test',          path: 'mgk7mb_test:MGK7MBBenchTests.insp_test',       required: yes, require_serial_number: yes, dependencies: null}
    res:   {description: 'Resistance test',          path: 'mgk7mb_test:MGK7MBBenchTests.res_test',        required: yes, require_serial_number: yes, dependencies: null}
    powup: {description: 'Powerup test',             path: 'mgk7mb_test:MGK7MBBenchTests.powerup_test',    required: yes, require_serial_number: yes, dependencies: null}
    pll:   {description: 'Program PLL',              path: 'mgk7mb_test:MGK7MBBenchTests.pll_test',        required: yes, require_serial_number: yes, dependencies: null}
    mem:   {description: 'Test ARM memory',          path: 'mgk7mb_test:MGK7MBBenchTests.mem_test',        required: yes, require_serial_number: yes, dependencies: null}
    sens:  {description: 'Read board power sensors', path: 'mgk7mb_test:MGK7MBNetworkTests.sens_test',     required: yes, require_serial_number: yes, dependencies: null}
    ser:   {description: 'Save serial number',       path: 'mgk7mb_test:MGK7MBNetworkTests.ser_test',      required: yes, require_serial_number: yes, dependencies: null}
    i2c:   {description: 'ARM i2c bus tests',        path: 'mgk7mb_test:MGK7MBNetworkTests.i2c_test',      required: yes, require_serial_number: yes, dependencies: null}
    fpga:  {description: 'FPGA tests',               path: 'mgk7mb_test:MGK7MBNetworkTests.fpga_test',     required: yes, require_serial_number: yes, dependencies: null}
    gtx:   {description: 'GTX testing',              path: 'mgk7mb_test:MGK7MBNetworkTests.gtx_test',      required: yes, require_serial_number: yes, dependencies: null}
    mezz:  {description: 'Basic mezz test',          path: 'mgk7mb_test:MGK7MBNetworkTests.mezz_test',     required: yes, require_serial_number: yes, dependencies: null}
    rmp:   {description: 'Ramp testing',             path: 'mgk7mb_test:MGK7MBNetworkTests.ramp_test',      required: yes, require_serial_number: yes, dependencies: null}
    clk:   {description: 'Clock testing',            path: 'mgk7mb_test:MGK7MBNetworkTests.clock_test',    required: yes, require_serial_number: yes, dependencies: null}
    qsfp:  {description: 'QSFP testing',             path: 'mgk7mb_test:MGK7MBNetworkTests.qsfp_test',     required: yes, require_serial_number: yes, dependencies: null}
menu:
    # The menu item will match the user input to either the 'key' field or to the regular expression 'regex'. The matching dictionary is returned.
    # If a regular expression is given, string parameters are replaced by string_param.format(regex_matched_group_list), i.e. '{0}' is replaced by the first matched group etc. The 'key' and 'regex' fields are excluded from this conversion.
    # Entry types are:
    #  test: a test to run. test_tag refers to the test to run in test_list (defined above). A regex entry will be added to match the tets tag and tets path. The description will be taken from the test description if none is provided here.
    #  exit: exit the menu
    #  text: do nothing. The description is shown in the menu if there is one.
    #  board_info: Sets the current board model and serial number. The serial number can be extracted from string parsed by the regex
    #
    - { description: "Start by entering the MB's serial number, then select a test or range of tests (e.g. 10-13).",     type: text}
    - { key: '1',                    action: run_test, test_tag: insp}
    - { key: '2',                    action: run_test, test_tag: res}
    - { key: '3',                    action: run_test, test_tag: powup}
    - { key: '4',                    action: run_test, test_tag: pll}
    - { key: '5',                    action: run_test, test_tag: mem}
    - { key: '6',                    action: run_test, test_tag: ser}   #used to be test 8, now is 6
    - { key: '7',                    action: run_test, test_tag: clk}   #used to be test 9, now is 7
    - { key: '8',                    action: run_test, test_tag: i2c}   #used to be test 6, now is 8
    - { key: '9',                    action: run_test, test_tag: sens}  #used to be test 7, now is 9
    - { key: '10',                   action: run_test, test_tag: fpga}
    - { key: '11',                   action: run_test, test_tag: qsfp} #used to be test 12, now is 11
    - { key: '12',                   action: run_test, test_tag: gtx}  #used to be test 14, now is 12
    - { key: '13',                   action: run_test, test_tag: mezz} #used to be test 11, now is 13
    - { key: '14',                   action: run_test, test_tag: rmp}  #used to be test 13, now is 14
    - { regex: '(\d+\-\d+)',         action: run_range,   input: '{0}'} # regex to select a range of options
    - { regex: '(0\d{3})',                             model: 'MGK7MB', serial: '{0}', next_key: '1'}  # 0nnn are MGK7MB Serial number
    - { regex: '38355-0000-(\d{4})',                   model: 'MGK7MB', serial: '{0}', next_key: '1'}  #38355-0000-nnnn are MGK7MB Serial nnnn
    - { key: 'S',                    action: push,    description: 'Send all new test results data to McGill'}
    - { key: 'R',                    action: summary, description: 'Generate summary of all tests'           }
    - { key: 'Q',                    action: exit,    description: 'Exit'                                    }


##################################
# Test-specific parameters
##################################

motherboard_tests:
    network:
         instruments: [ps18v] # Subset of instruments we use in the network tests

    impedance:
        instruments: [dmm]
        max_impedance: 1.0e+10  # any measurement more than this is probably not taken correctly
        test_points:
        # delay: delay to wait before taking the measurement
        # zmin: minimum impedance below which the test will fail
           - ['+V (P18)',       {delay: 0.2, zmin: 250}]
           - ['12V (L3)',       {delay: 0.2, zmin: 250}]
           - ['Vadj (L11)',     {delay: 0.2, zmin: 250}]
           - ['3.3V (L1)',      {delay: 0.2, zmin: 15}]
           - ['5V (L4)',        {delay: 0.2, zmin: 250}]
           - ['1V Gt. (L5)',    {delay: 0.2, zmin: 13}]
           - ['1.2V Gt. (L6)',  {delay: 0.2, zmin: 150}]
           - ['1V Co. (L8)',    {delay: 0.2, zmin: 13}]
           - ['1.5V (L7)',      {delay: 0.2, zmin: 200}]
           - ['1.8V (L9)',      {delay: 0.2, zmin: 150}]

    powerup:
        instruments: [ps18v]
        vlt: 18
        curlmt: 2
        imax: 1
        imin: 0.5

    pll:
        instruments: [ps18v]
        vlt: 18
        curlmt: 2
        pll1regs:
            - 0x01260320
            - 0xEB060301
            - 0x011E0302
            - 0xEB040303
            - 0xEB860314
            - 0x101C1E75
            - 0x849F4FE6
            - 0xBDB23BE7
            #- 0x20009CF8
        pll2regs:
            - 0xEB840320
            - 0xEB840301
            - 0xEB840302
            - 0xEB860303
            - 0xEB400014
            - 0x101C1E75
            - 0x84BF49A6
            - 0xBDB23BE7
            #- 0x20009DD8

    mem_test:
        instruments: [ps18v]
        vlt: 18
        curlmt: 5

    sensors:
        vlt: 18
        curlmt: 5

        current:
            VCC3V3:     {nom: 2.00,  pmargin: 0.30,  amargin: 0}     # 30%
            VCC12V0:    {nom: 0.1,  pmargin: 0.0,  amargin: 0.1}   # +-100mA
            VCC5V5:     {nom: 1.069, pmargin: 0.30,  amargin: 0}     # 30%
            VCC1V0_GTX: {nom: 3.8,   pmargin: 0.00,  amargin: 4}  # +-1A (Change by R.Dubois for A.Gilbert 170922)
            VCC1V0:     {nom: -3.8,   pmargin: 0.00,  amargin: 4}   # +-1A (Change by R.Dubois for A.Gilbert 170922)
            VCC1V2:     {nom: 0.020, pmargin: 0.00,  amargin: 0.020} # +-20mA
            VCC1V5:     {nom: 1.644, pmargin: 0.30,  amargin: 0}     # 30%
            VCC1V8:     {nom: 0.275, pmargin: 0.30,  amargin: 0}     # 30%
            VADJ:       {nom: 0.023, pmargin: 0.00,  amargin: 0.03}  # +-30mA

        voltage:
            VCC3V3:     {nom: 3.3,   pmargin: 0.05,  amargin: 0}     # 5%
            VCC12V0:    {nom: 12,    pmargin: 0.05,  amargin: 0}     # 5%
            VCC5V5:     {nom: 5.5,   pmargin: 0.05,  amargin: 0}     # 5%
            VCC1V0_GTX: {nom: 1.05,  pmargin: 0.05,  amargin: 0}     # 5%
            VCC1V0:     {nom: 1,     pmargin: 0.05,  amargin: 0}     # 5%
            VCC1V2:     {nom: 1.2,   pmargin: 0.05,  amargin: 0}     # 5%
            VCC1V5:     {nom: 1.5,   pmargin: 0.05,  amargin: 0}     # 5%
            VCC1V8:     {nom: 1.8,   pmargin: 0.05,  amargin: 0}     # 5%
            VADJ:       {nom: 2.5,   pmargin: 0.05,  amargin: 0}     # 5%

        temp:
            POWER:      {nom: 30,     pmargin: 0.00,  amargin: 25}   # +-25 C
            FPGA:       {nom: 30,     pmargin: 0.00,  amargin: 25}   # +-25 C
            ARM:        {nom: 30,     pmargin: 0.00,  amargin: 25}   # +-25 C
            PHY:        {nom: 30,     pmargin: 0.00,  amargin: 25}   # +-25 C

        fmccurrent:
            VCC3V3:     {nom: 0,     pmargin: 0.00,  amargin: 0.005}   # +-5mA
            VCC12V0:    {nom: 0,     pmargin: 0.00,  amargin: 0.005}   # +-5mA
            VADJ:       {nom: 0,     pmargin: 0.00,  amargin: 0.005}   # +-5mA

        fmcvoltage:
            VCC3V3:     {nom: 3.3,   pmargin: 0.05,  amargin: 0}     # 5%
            VCC12V0:    {nom: 12,    pmargin: 0.05,  amargin: 0}     # 5%
            VADJ:       {nom: 2.5,   pmargin: 0.05,  amargin: 0}     # 5%

        fmcoffvoltage:
            VCC3V3:     {nom: 0.4,   pmargin: 0.00,  amargin: 0.4}     # +-0.4V
            VCC12V0:    {nom: 0.4,   pmargin: 0.00,  amargin: 0.4}     # +-0.4V
            VADJ:       {nom: 0.4,   pmargin: 0.00,  amargin: 0.4}     # +-0.4V

    ser_test:
        vlt: 18
        curlmt: 5
        rev: 4

    i2c_test:
        vlt: 18
        curlmt: 5

    clock_test:
        vlt: 18
        curlmt: 2

    fpga_test:
        vlt: 18
        curlmt: 5

    mezz_test:
        vlt: 18
        curlmt: 5
        fmccurrent:
            VCC3V3:     {nom: 2,     pmargin: 0.00,  amargin: 2}   # +-1A
            VCC12V0:    {nom: 0.1,     pmargin: 0.00,  amargin: 0.1}   # +-100mA
            VADJ:       {nom: 0.115,   pmargin: 0.00,  amargin: 0.05}   # +-0mA

        fmcvoltage:
            VCC3V3:     {nom: 3.3,   pmargin: 0.05,  amargin: 0}     # 5%
            VCC12V0:    {nom: 12,    pmargin: 0.05,  amargin: 0}     # 5%
            VADJ:       {nom: 2.5,   pmargin: 0.05,  amargin: 0}     # 5%

    rmp_test:
        vlt: 18
        curlmt: 5

    qsfp_test:
        vlt: 18
        curlmt: 5
        manufacturer: "3M Company"
#        serial: "V10E6005"
        serial: "V20B9886"

    gtx_test:
        vlt: 18
        curlmt: 5
        tx_power: 9
        bp_limit: 1.e-10
        qsfp_limit: 1.e-10
        gpu_limit: 50
