""" Nose plugin and utilities used to store, process and publish high quality test reports.



TODO:
    150612 JFC:
                - Handle when test targets are missing
                - Improve XML and RST report structure
                   - Add test run synopsis table with hyperlinks
                   - use different nodes for  output, Error/Failures, Logs so we can have different colors and make parsing easier
                   - Add context, summary and synopsis tables to rST reports
                - Have attachment links renamed at the time of saving so we don't have to know the name of the Rst file when the document is being built.
                - Capture system exit message (when argparse.parse generates an error in the test suites)
                - Add xr.table() to generate nice tables. XML template will have to deal with it.
                - Add xr.rst_on() and xr.rst_off() to allow standard output to be parsed as restructuredText by default without having to use the xr.rst() command.
"""
import traceback
import sys
import os
import logging
import nose
from StringIO import StringIO
from nose.plugins import Plugin
import textwrap

import inspect
import datetime

import test_report
from namespace import NameSpace



# ---------------------------------------------------------
# Utility attributes and functions availalable to the tests
# ---------------------------------------------------------

import functools

class XReport(Plugin):
    """Nose plugin the capture all test data and test results and package it
    into a TestReport object which can be easily queried or used to generate
    HTML, PDF or Restructured Text reports.

    Xreport will capture all ``nosetests`` command-line arguments after the --xargs
    parameter and make them available to unittest.TestCase instances and modulein order
    to parametrize the tests from the command line.

    Plots generated by matplotlib can also be embedded in the test data and
    will be correctly rendered in all output formats.
    """
    instance = None  # Used to make sure we only ever run one instance of the plugin
    name = 'xreport'
    score = 2  # run late so we can capture all stdout and all remaining command line arguments

    class instancemethod(object):
        """ Decorator that ensures that if a method is called from a class,
            its first argument (self) is the currently active singleton
            instance found in the class attribute ``instance``. (i.e.
            a.fn(args) = fn(a,args) and A.fn(args) = fn(A.instance, args))

            Note that the first argument (self) could be None if there is no
            currently active instance of the class.  The method must check for
            that.

            This is conceptually doing the opposite of the classmethod
            decorator, which ensures that the first argument of a function is
            always a class whether we call it from a class or an instance of
            the class.

        """
        def __init__(self, func):
            self.func = func
        def __get__(self, instance, instance_type):
            inst = instance or instance_type.instance
            return functools.update_wrapper(lambda *args, **kwargs: self.func(inst, *args, **kwargs), self.func)

    class instanceproperty(object):
        """ Decorator that returns a property that can be accessed from the class as well as the instance of a class."""
        def __init__(self, func):
            if isinstance(func, str):
                self.func = lambda s: getattr(s,func)
            else:
                self.func = func
        def __get__(self, instance, instance_type):
            inst = instance or instance_type.instance
            return self.func(inst)


    @instanceproperty
    def params(self):
        """ Returns the parameters passed to the XReport plugin object when it was instantiated. Returns None if the Xreport plug-in is not used. """
        return self.xparams if self else None

    @instanceproperty
    def args(self):
        """ Returns the nose command line arguments following --xargs. Those can be parsed directly by argparse.parse. Returns an empty list if the Xreport plugin is not used. """
        return self.xargs if self else []


    @instancemethod
    def func(self, x):
        """ This is a docstring"""
        print self, x

    @classmethod
    def generate_test_summary(cls, *args, **kwargs):
        return test_report.generate_test_summary(*args, **kwargs)


    @classmethod
    def _no_plugin(cls, feature):
        raise Warning('The Xreport plugin is not active. %s will be ignored' % feature)

    @classmethod
    def insert_plot(cls, *args, **kwargs):
        if cls.instance:
            cls.instance._insert_plot(*args, **kwargs)
        else:
            cls._no_plugin('Plots')

    @classmethod
    def output(cls, message):
        if cls.instance:
            cls.instance._output(message)
        else:
            print message

    @classmethod
    def header(cls, text):
        if cls.instance:
            cls.instance._add_header(text)
        else:
            print text
            print '-' * len(text)

    @classmethod
    def input(cls, message):
        answer = raw_input(message)
        # Send a copy of the message and answer to the capture buffer because
        # raw_input bypasses stdout for some reason.
        if cls.instance:
            cls.instance._buf._write(str(message)+answer+'\n')
        return answer


    @classmethod
    def pass_fail(cls, test):
        return ['FAIL','PASS'][bool(test)]

    @classmethod
    def new_block(cls):
        if cls.instance:
            cls.instance._flush()
        else:
            print '-------------------------------------------------------------'

    @classmethod
    def save_data(cls, data):
        if cls.instance:
            cls.instance._save_data(data)

    @classmethod
    def get_params(cls):
        if cls.instance:
            return cls.instance.xparams

    @classmethod
    def rst(cls, message):
        if cls.instance:
            cls.instance.pprint(message)
        else:
            print message

    def __init__(self, xfile=None, xformat=[], xparams={}):
        """ Create a Xreport nose plugin instance that can be passed to the nose test engine.

        If ``xfile`` is specified, the test data and report will be saved in
        the spficied filename in the formats listed in ``xformat``.

        The object specified by ``xparams`` will be accessible by the test
        functions or methods through the ``params`` attribute of the Xreport
        class.
        """
        super(XReport, self).__init__()
        self.xfile = xfile
        self.xformat = xformat
        self.xparams = xparams
        self.xargs = []
        self.stdout = []
        self._buf = None
        self.enabled = True
        self.original_stdout = sys.stdout
        self.stream = sys.stdout
        self.logger = logging.getLogger('')
        # self.rep = TestReport()
        self.rep = None
        type(self).instance = self  # This the the currently active instance now

    def check_instance(self):
        if self is not self.instance:
            raise RuntimeError('A method was called with an XReport instance that is not the currently active instance. The API offered to the test always use the current instance, so previous instances should not be used anymore.')


    def options(self, parser, env):
        """Register commandline options and grab all options after --xargs to
        pass on to the test suites.
        """
        def gobble_all_remaining_args(option, opt_str, value, parser):
            self.logger.debug('Capturing xargs arguments:%r' % (parser.rargs))
            self.xargs = []
            while parser.rargs:  # Steal all following argss
                self.xargs.append(parser.rargs.pop(0))

        def split_args(option, opt_str, value, parser):
            self.logger.debug('Splitting arguments:%s' % (value))
            args = value.replace(',', ' ').split()
            while parser.rargs and not parser.rargs[0].startswith('-'):  # Steal all following args until '-'
                args.append(parser.rargs.pop(0))
            setattr(parser.values, option.dest, args)

        self.check_instance()

        parser.add_option(
            "--xreport-file", "--xfile",
            action="store",
            dest='xreport_file',
            # default=env.get('NOSE_XREPORT_FILE', './test'),
            default=None,
            help='Report output path and base filename, without extension. The output files will be appended by .xml, .rst and _attachment_id.png')
        parser.add_option(
            "--xformat",
            action="callback",
            callback=split_args,
            type='string',
            dest='xformat',
            default=['pdf'],
            help='Output format in addition to the xml file: pdf or rst')
        # parser.add_option(
        #     '--xquiet',
        #     action="store_true",
        #     dest="xquiet",
        #     default=False)
        parser.add_option( # This must be the last option since it gobbles everything else...
            "--xargs",
            action="callback",
            callback=gobble_all_remaining_args,
            help='Any arguments that follow will be grabbed and made accessible to the tests as the `xargs` attribute of the xreport module.')

    def configure(self, options, conf):
        """Configure plugin. Plugin is enabled by default.
        """
        super(XReport, self).configure(options, conf)
        self.conf = conf  # debug
        self.options = options
        self.enabled = True  # Plugin is enabled by default
        self.logger.debug('Config is %s' % conf)
        self.verbose = options.verbosity

        self.filename = self.xfile or options.xreport_file
        self.formats = set(self.xformat) | set(options.xformat)

        self.rep = test_report.TestReport()
        test_date = datetime.datetime.now().isoformat()
        self.rep.add_context_table([
            ['Run start date/time',    test_date],
            ['Xargs',                  self.xargs],
            ['Command line arguments', sys.argv],
            ['Target file name',       '(undefined)']
            ])
        self.rep.add_group_info(
            title='Test Run',
            test_name='(test run)',
            test_path='(test run)',
            test_date=test_date
            )
        # self.stream.write('Test Run (%s)\n\n' % test_date)
        # self.conf = conf
        # if not options.capture:
        #     self.enabled = False
        self.check_instance()
        self.logger.debug('Config is done')

    def setOutputStream(self, stream):
        """Intercept output stream configuration and forward to a dummy device."""
        # return dummy stream
        class DummyIO:
            def write(self, *arg):
                pass
            def writeln(self, *arg):
                pass
            def flush(self):
                pass

        stream.flush()
        # If we are verbose, send all text to screen, else send to dummy device

        if self.verbose:
            self.stream = stream
        else:
            self.stream = DummyIO()


        return DummyIO()  # Discard any text generated by nose itself

    def start_stdout_capture(self):
        """ Redirect Stdout in a StringIO"""
        class StringStdIO(StringIO):
            """ StringIO object augmented to send a copy to ``stdout``"""
            def __init__(self, stdout, *args):
                self._stdout = stdout
                StringIO.__init__(self, *args)
            def write(self, *arg):
                self._stdout.write(*arg)
                self._stdout.flush()
                StringIO.write(self, *arg)
            def _write(self, *arg):
                StringIO.write(self, *arg)
            # def writeln(self, *arg):
            #     self._stdout.writeln(*arg)
            #     self._stdout.flush()
            #     StringIO.writeln(self, *arg)
            # def _writeln(self, *arg):
            #     StringIO.writeln(self, *arg)
            def flush(self):
                self._stdout.flush()
                StringIO.flush(self)

        sys.stdout.flush()
        self.stdout.append(sys.stdout)
        self._buf = StringStdIO(self.stream)
        sys.stdout = self._buf

    def stop_stdout_capture(self):
        """ Restore the original stdout device"""
        buf = self._buf.getvalue()
        if self.stdout:
            sys.stdout = self.stdout.pop()
        return buf

    def flush_stdout_capture(self):
        """Get currently captured output and flush buffer"""
        self._buf.flush()
        buf = self._buf.getvalue()
        self._buf.truncate(0)
        return buf

    def _output(self, message):
        """ Prints an interactive message to the user """
        self.original_stdout.write(message + '\n')
        self.original_stdout.flush()

    def _flush(self):
        """ Flush the current standard output and start a new block of text."""
        captured_output = self.flush_stdout_capture()
        if captured_output:
            self.rep.add_literal_text_block(captured_output)  # Add any stdout capture
            # self.stream.write(captured_output)

    def _insert_plot(self, caption='', format='png'):
        """ Insert a matplotlib plot in the test report"""
        # insert whatever captured text we have so far
        self._flush()
        self.rep.add_plot(caption=caption, format=format)

    def pprint(self, text, dedent=True):
        """ Add a block of text verbatim to be interpreted a reStructuredText"""

        self._flush()
        if dedent:
            text = textwrap.dedent(text)
        self.rep.add_text_block(text)
        self.stream.write(text)

    def _add_header(self, text):
        self._flush()
        self.rep.add_header(text)
        self.stream.write('\n' + text + '\n')
        self.stream.write('-' * len(text) + '\n')

    def _save_data(self, data):
        self.rep.add_data(data)

    def begin(self):
        """Initialize the test run.
        """
        self.logger.info('begin - xargs= %s on xreport module ID %s ' % (self.xargs, type(self).__module__))
        self.check_instance()

        self.start_stdout_capture()  # get an early handle on sys.stdout

        self.logger.info('begin - done')

    def startContext(self, ctx):
        self.last_context = ctx  # for debug
        self.logger.info('StartContext %s' % ctx)
        try:
            group_name = ctx.__name__
        except AttributeError:
            group_name = str(ctx)

        # If this is a module, get the path
        try:
            path = ctx.__file__.replace('.pyc', '.py')
        except AttributeError:
            path = '...unknown...'

        title, description = self._get_doc(ctx)
        context_type = ('MODULE' if inspect.ismodule(ctx) else
                        'GENERATOR' if inspect.isgeneratorfunction(ctx) else
                        'CLASS' if inspect.isclass(ctx) else '')
        self.rep.enter_group_node(group_name)
        full_title = context_type + ' ' + self.rep.get_node_path()
        test_datetime = datetime.datetime.now().isoformat()
        self.rep.add_group_info(
            test_name=self.rep.get_node_path(),
            title=full_title,
            test_path=self.rep.get_node_path(),
            test_date=test_datetime,
            short_description=title,
            long_description=description
            )

        self.stream.write('%s (%s)\n\n' % (full_title, test_datetime))
        self.logger.info('StartContext %s completed' % ctx)

    def all_nodes_passed(self):
        """ gather the pass/fail node of every underlying test case or group"""
        if not self.rep.node_tail:
            print 'all_nodes_passed: There is no tail node!'
            return
        return all([n.passed.text == 'true' for n in self.rep.get_current_node().iterchildren(['case', 'group'])])

    def stopContext(self, ctx):
        self.logger.info('StopContext %s, etree=%s' % (ctx, self.rep.etree))
        self.rep.add_passed_node(self.all_nodes_passed())
        self.rep.exit_node()
        self.logger.info('StopContext %s Completed' % (ctx))

    def beforeTest(self, test):
        """Flush capture buffer.
        """
        self.logger.info('beforeTest %s' % test)
        self.start_stdout_capture()

    def startTest(self, test):
        self.last_test = test  # debug

        if isinstance(test.test, nose.case.FunctionTestCase):
            test_type = 'FUNCTION'
            test_name = test.test.test.func_name
            summary, description = self._get_doc(test.test.test)
        elif hasattr(test.test, '_testMethodName'):
            test_type = 'METHOD'
            if hasattr(test.test,'test'):
                test_name = test.test.test.func_name
                summary, description = self._get_doc(test.test.test)
            else:
                test_name = test.test._testMethodName
                summary, description = self._get_doc(test.test._testMethodDoc)
        else:
            test_type = str(type(test.test))
            test_name = type(test.test).__name__
            summary, description = self._get_doc(test.test)  # ? Not sure yet what to do here if this ever happens
        test_args = str(getattr(test.test, 'arg', "()")).replace(',)', ')')

        self.rep.enter_case_node(test_name)  # Begin new node. Must be before we use get_node_path()

        title = '%s %s%s' % (test_type, self.rep.get_node_path(), test_args)
        self.logger.info('startTest %s' % test_name)
        test_date = datetime.datetime.now().isoformat()
        self.rep.add_group_info(
            title=title,
            test_name=test_name,
            test_path=self.rep.get_node_path(),
            test_date=test_date,
            test_args=test_args,
            short_description=summary,
            long_description=description
            )
        self.stream.write('%s (%s)\n\n' % (title, test_date))


    def stopTest(self, test):
        self.logger.info('stopTest %s ' % test)

    def afterTest(self, test):
        """Clear capture buffer.
        """
        self.logger.info('afterTest %s' % test)
        self._flush()
        self.stop_stdout_capture()
        self.rep.exit_node()

    def addSuccess(self, test):
        self.logger.info('addSuccess %s' % test)
        print
        print ' ---> TEST PASSED:\n'
        self.rep.add_passed_node(True)
        self.passed = True

    def addError(self, test, err):
        self.logger.info('addError %s' % test)
        summary = err[1][:err[1].find('\n--------')].replace('\n',' ')  # Strip captured stdout or logs from summary text
        print
        print ' ---> ERROR: %s\n' % (summary)
        self._flush()
        self.rep.add_summary(summary)
        err = self.formatErr(err)
        self.logger.info('addError %s\n%s' % (summary, err[-1000:]))
        self._add_header('Error report')
        self.rep.add_literal_text_block(err)  #
        self.rep.add_passed_node(False)
        self.stream.write('\n%s\n' % (err))
        self.passed = False

    def addFailure(self, test, err):
        self.logger.info('addFailure %s' % test)
        summary = err[1][:err[1].find('\n--------')].replace('\n',' ')
        print
        print ' ---> FAILURE: %s\n' % (summary)
        self._flush()
        self.rep.add_summary(summary)
        err = self.formatErr(err)
        self.logger.info('addFailure %s\n%s' % (summary, err[-1000:]))
        self._add_header('Failure report')
        self.rep.add_literal_text_block(err) #
        self.rep.add_passed_node(False)
        self.stream.write('\n%s\n' % (err))
        self.passed = False

    def formatFailure(self, test, err):
        """Add captured output to failure report.
        """
        return self.formatError(test, err)

    def formatErr(self, err):
        exctype, value, tb = err
        return ''.join(traceback.format_exception(exctype, value, tb))

    def formatError(self, test, err):
        """Add captured output to error report.
        """
        ec, ev, tb = err
        return (ec, str(ev), tb)

    def finalize(self, result):
        """
        """
        self.logger.info('Finalize')
        # Restore stdout.
        while self.stdout:
            self.stop_stdout_capture()

        self.rep.add_passed_node(self.all_nodes_passed())

        number_of_tests = result.testsRun

        self.stream.write('-----------------------------------------\n')

        if not result.wasSuccessful():
            self.rep.add_literal_text_block('Ran %d tests: FAILED (failures=%d, errors=%d)' % (number_of_tests, len(result.failures),len(result.errors)))
        else:
            self.rep.add_literal_text_block('Ran %d tests: SUCCESS' % number_of_tests)

        synopsis = '\n'.join(self.rep.get_synopsis_as_strings())
        self.rep.add_literal_text_block(synopsis)
        self.stream.write('%s\n' % synopsis)

        sys.stdout = self.original_stdout

        if self.filename:
            self.write(self.filename, self.formats)

    def write(self, filename, formats=[]):
        self.rep.write(filename=filename, formats=formats)

    @staticmethod
    def _get_doc(thing):
        '''Try to convert DocStrings into a (title, description) tuple.'''

        # Grab information from DocStrings
        if isinstance(thing, str):
            doc = thing
        else:
            doc = inspect.getdoc(thing) or 'No doctring'
        title = doc.splitlines()[0]
        description = '\n'.join(doc.splitlines()[1:])

        # # Markup to HTML
        # title = docutils.core.publish_parts(title, writer_name='html')['body']
        # description = docutils.core.publish_parts(description, writer_name='html')['body']

        # # Markupify and parse into XHTML
        # title = lxml.html.fromstring(title)
        # description = lxml.html.fragments_fromstring(description)

        return (title, description)


    @classmethod
    def run_from_module(cls):
        """ Run the nose tests with the XReport plugin loaded and activated on the currently executed module.
        """
        argv = sys.argv
        module_name, __ = os.path.splitext(argv[0])  # remove .py extension from module name
        # if not argv[1].startswith(
        return cls.run([module_name] + argv[1:])

    @classmethod
    def run(cls, test_path, log_level='WARNING', xfile=None, xformat=[], xparams={}):
        """ Run nose on the test specified in the specified ``test_path`` (e.g
        'module_name:class_name.method_name' or any other nose path) using the Xreport plugin to
        capture the text and data generated by the test.

        Returns the XReport instance.
        """
        import logging.handlers
        log_handler = logging.handlers.SysLogHandler()
        logger = logging.getLogger('')
        logger.handlers = []  # Clear all existing handlers
        logger.setLevel(log_level)
        logger.addHandler(log_handler)

        xreport = cls(xfile=xfile, xformat=xformat, xparams=xparams)  # Plugin is enabled by default. No need to use the option --with-xreport
        sys.stdout.flush()
        nose.run(argv=[sys.argv[0], test_path] + sys.argv[1:], addplugins=[xreport])
        return xreport




def main():
    """ Run the nose tests with the XReport plugin loaded and activated, and
    save the XML and RST reports using the specified ``filename`` prefix.
    """
    import logging.handlers
    log_handler = logging.handlers.SysLogHandler()
    logger = logging.getLogger('')
    logger.handlers = []  # Clear all existing handlers
    logger.setLevel(logging.DEBUG)
    logger.addHandler(log_handler)

    import xreport as xr
    xr.XReport.instance = None  # (debug) Bypass check to allow creation of a new instance of the plugin
    x = xr.XReport()  # Plugin is enabled by default. No need to use the option --with-xreport
    nose.run(addplugins=[x])
    return x

if __name__ == '__main__':
    x = main()
