# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

# Try to get the version number from git first for in the case where we are working out of
# an editable install (-e), in which case the version file might be stale unless we manally
# reinstall periodically. If we are not in a git repo, which is the case when the installer moved the file in the package folder,
# use the version that is saved in the version file during install.
try:
    import setuptools_scm
    __version__ = setuptools_scm.get_version(root='..', relative_to=__file__)
except (ImportError, LookupError):
    try:
        from ._version_scm  import version as __version__
    except (ImportError):
        raise RuntimeError('Cannot determine version')
