"""
FUNCGEN.py module
 Implements interface to the internal function generator

History:
    2012-10-01 JFC : Created from SRCSEL.py
    2012-10-17 JFC: Sets ramp as default function
"""

from ..mmi import MMI, BitField
import numpy as np
import asyncio

#ADD METHOD TO SET NUMBER OF FRAMES OVER WHICH WE COUNT SAMPLES OVERFLOWS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
class FUNCGEN(MMI):
    """ Implements interface to the function generator within a procecessor
    pipeline"""
    # Create local variables for page numbers tomake the table more readable
    CONTROL = BitField.CONTROL
    STATUS = BitField.STATUS

    # Memory-mapped register definition
    RESET            = BitField(CONTROL, 0x00, 7, doc='Resets this module')
    ENABLE           = BitField(CONTROL, 0x00, 6, doc="doc")
    RAM_PAGE_LSB     = BitField(CONTROL, 0x00, 3, width=3, doc="LSB of the 512-byte RAM page we want to access")
    FUNCTION         = BitField(CONTROL, 0x00, 0, width=3, doc="Selects the source of the signal to be generated")
    BYTE_A           = BitField(CONTROL, 0x01, 0, width=8, doc="Byte A to be used by the function generator")
    BYTE_B           = BitField(CONTROL, 0x02, 0, width=8, doc="Byte B to be used by the function generator")
    STATS_PERIOD     = BitField(CONTROL, 0x04, 0, width=16, doc="Number of frames to send. If 0, send continuously")
    # FUNCTION_NUMBER  = BitField(CONTROL, 0x04, 0, width=8, doc="Function number stored in buffer") --deprecate
    RST_LFSR         = BitField(CONTROL, 0x06, 6, width=1, doc="Reset the noise generator to inject seed for LFSR")
    FUNCTION_NUMBER  = BitField(CONTROL, 0x06, 4, width=2, doc="Function number stored in buffer")
    SHIFT            = BitField(CONTROL, 0x05, 0, width=4, doc="Number of bits to shift-right the ADC data before it is passed on")
    RAM_PAGE_MSB     = BitField(CONTROL, 0x05, 4, width=4, doc="MSB of the 512-byte RAM page we want to access")
    STATS_ENABLE     = BitField(CONTROL, 0x06, 7, doc="Enables overflow_ctr update. Clears stats_done when stats_enabled cleared.")
    CLIP_WIDTH       = BitField(CONTROL, 0x00, 4, doc="Saturates the output data to a ``clip_width-1``-bit wide signed value (i.e. clip_width is the position of the sign bit). Saturation is applied after the right-shift. ")
    FUNCTION_NUMBER  = BitField(CONTROL, 0x07, 0, width=8, doc="Function number stored in buffer")

    RAMP_CTR   = BitField(STATUS, 0x00, 0, width=8, doc="Last 8 bits of the ramp counter (for debuging)")
    FRAME_CTR  = BitField(STATUS, 0x01, 0, width=8, doc="Frame counter")
    FRAME_OVERFLOW_FLAG = BitField(STATUS, 0x02, 2, doc="Indicates if there is at least an adc overflow in current frame.")
    STATS_DONE = BitField(STATUS, 0x02, 1, doc="overflow_ctr ready with new value for new integration period")
    SEND_FRAME = BitField(STATUS, 0x02, 0, doc="debug")
    DELAY_CTR = BitField(STATUS, 0x04, 0, width=16, doc="Debug: Delay counter")
    OVERFLOW_CTR = BitField(STATUS, 0x08, 0, width=32, doc="Number of ADC overflows since the counter was last cleared")

    FN_ADC = 0
    FN_BUFFER = 1
    FN_NOISE = 2
    FN_WORD_CTR = 3
    FN_FRAME8 = 4
    FN_FRAME4 = 5
    FN_BUFFER_NIBBLE4 = 6
    FN_ADC16 = 7 # *deprecated*

    # The following define the source of the data
    DATA_SOURCE_NAMES = {
        'adc':                   FN_ADC,  # Sends the ADC data
        'adc16':                 FN_ADC16,  # Sends the every other sample of ADC data in 16 bit, MSB first
        'noise':                 FN_NOISE,  # Uniform white noise generator
        'word_ctr_buffer_flags': FN_WORD_CTR,  # 32-bit Frame/word counter, with ADC overflow from bit 0 of buffer bytes
        'buffer':                FN_BUFFER,  # Sends the data stored in the buffer
        'funcgen':               FN_BUFFER,  # Sends the data stored in the buffer (for backwards compatibility)
        'frame8':                FN_FRAME8,  # Sends the frame number in every 8-bit sample
        'frame4':                FN_FRAME4,  # Sends the frame number if the upper 4 bits of each samples. The lower bits are zero.
        'nibble4':               FN_BUFFER_NIBBLE4,  # Sends the lower/upper nibble of the bytes in the buffer as a real value based on whether the frame number is even/odd.
        }


    def one(self):
        """ Return complex values (1+0j) as if generated by the scaler in 4-bit mode with offset encoding.
        """
        v = np.full((self.NB//2, 2), (1+8, 0+8)).ravel() << (self.Nbits - 4) # with the offset encoding, 9s here result in 1s in the complex visibility data
        return v

    def freq_test(self, freq_test_bins=[]):
        N = min(len(freq_test_bins), 108) # N has to be less that 108 for this to work
        freq_pattern_real = np.array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
                                       2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
                                       3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,
                                       4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,
                                       6,  6,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  9,  9,
                                       9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12,
                                       13, 13, 13, 14, 14, 15], dtype=np.uint8) << (self.Nbits - 4)
        freq_pattern_imag = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  2,  3,
                                        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  3,  4,  5,  6,  7,
                                        8,  9, 10, 11, 12, 13, 14, 15,  4,  5,  6,  8,  9, 10, 11, 12, 13,
                                       14, 15,  6,  7,  8,  9, 11, 12, 13, 14, 15,  6,  8,  9, 10, 11, 12,
                                       14, 15,  7,  8, 10, 12, 13, 14, 15,  8, 10, 12, 13, 14, 15,  9, 10,
                                       11, 12, 14, 15, 12, 13, 14, 15, 11, 12, 13, 14, 15, 12, 13, 14, 15,
                                       13, 14, 15, 14, 15, 15], dtype=np.uint8) << (self.Nbits - 4)
        v = np.zeros(self.NB, dtype=np.uint8)
        v_real = np.zeros(self.NB // 2, dtype=np.uint8)
        v_imag = np.zeros(self.NB // 2, dtype=np.uint8)
        v_real[freq_test_bins] = freq_pattern_real[:N]
        v_imag[freq_test_bins] = freq_pattern_imag[:N]
        v[::2] = v_real
        v[1::2] = v_imag
        return v


    FUNCTION_NAMES = {  # key : (function number, buffer generator fn)

        # The following define the patterns we can program in the waveform buffer
        # If the function returns a numpy array, it should be self.NS long; it will be reinterpreted as self.dtype type
        # If the function returns a bytestring, the bytes will be written directly into the buffer.

        # Warning!:
        #   - byte ordering and dtype are changed when using operators (>>, /, +, & etc).
        #   - Use N//2 to make sure  the arange is of integer type.
        'buffer':         (0, lambda buffer=None, self=None: buffer),  # Arbitrary waveform
        'arb':            (0, lambda data, self=None: data),  # Arbitrary waveform
        'a':              (1, lambda self, a: np.full(self.NS, a)),  # All bytes are Byte A. 16-bit friendly
        'b':              (2, lambda self, b: np.full(self.NS, b)),  # All bytes are Byte B
        'ab':             (3, lambda self, a, b, : np.tile((a , b ), self.NS // 2)),  # Bytes alternate between A and B.
        'ramp':           (4, lambda self, **kwargs: (np.arange(self.NS) - self.Nvalues / 2) % self.Nvalues - self.Nvalues / 2),  #  0 ... Nvalues/2-1, -Nvalues/2 ... 0
        'real_ramp':      (5, lambda self, **kwargs: np.ravel([(i,0) for i in range(self.NS//2)])),  # Generates the ramp: 0,0,1,0,2,0... If the data is read as (8+8)-bit complex value pairs, we obtain (0,0j), (1+0j)... (255+0j)
        '4bit_ramp':      (6, lambda self, **kwargs: np.arange(self.NS) << (self.Nbits - 4)),  # Generates the ramp in the upper 4 bits of the ADC sample (e.g for 8 bits: 0x00, 0x10, 0x20, ... 0xF0.)
        '8bit_ramp':      (15, lambda self, **kwargs: np.arange(self.NS) << (self.Nbits - 8)),  # Generates the ramp in the upper 4 bits of the ADC sample (e.g for 8 bits: 0x00, 0x10, 0x20, ... 0xF0.)
        '4bit_real_ramp': (7, lambda self, **kwargs: np.ravel([(i,0) for i in range(self.NS//2)]) << (self.Nbits - 4)),  # Generates the ramp: 0x00, 0x00, 0x10, 0x00, 0x20, 0x00 ... 0xF0, 0x00
         # '4bit_split_ramp': (0, FN_BUFFER, ),  # Generates 0x0000, 0x0010, 0x0020, .. 0x00F0, 0x1000, 0x1010 ...
        'sin':            (8, lambda self, freq=1, ampl=None: (np.sin(np.arange(self.NS) * 2 * np.pi / self.NS * freq) * (ampl if ampl is not None else ((1 << (self.Nbits - 1)) - 1) ))),
        'cos':            (8, lambda self, freq=1, ampl=None: (np.cos(np.arange(self.NS) * 2 * np.pi / self.NS * freq) * (ampl if ampl is not None else ((1 << (self.Nbits - 1)) - 1) ))),
        'crate_slot':     (9, lambda self: np.tile(self.fpga.get_id()[:2], self.NS // 2) << (self.Nbits - 4)),  # Bytes alternate between crate number and slot number (in upper 4 bits). If FFT and scaler are bypassed, then the complex data has the crate number in the real part and slot number in imag part.
        #'crate':          (10, lambda self, N=BUFFER_SIZE: np.tile(np.array([self.get_id()[0]<<4, 0], np.uint8), N / 2)),  # Bytes alternate between crate number (in upper 4 bits) and 0. If FFT and scaler are bypassed, then the complex data has the crate number in the real part.
        'freq_test':      (10, freq_test),
        'one':            (11, one), # complex value 1+0j in 4-bit mode & offset encoding
        # '4bit_complex_ramp': (12, lambda self=None: (((np.arange(self.NS // 2) & 0xf0) << 8) + ((np.arange(self.NS // 2) & 0xf) << 4)).astype('>u2').view('u1')),  # Generates the ramp: 0x00, 0x00, 0x00, 0x10, 0x00, 0x20 ... 0xF0, 0xF0. The corner turn interpret these as (0+0j), (0+1j,) ...  (0+15j), (1+0j), ... (15+15j)
        '4bit_complex_ramp':  (12, lambda self: np.ravel([((i>>4) & 0xf , i & 0xf) for i in range(self.NS//2)]) << (self.Nbits - 4)),  # Generates the ramp: 0x00, 0x00, 0x00, 0x10, 0x00, 0x20 ... 0xF0, 0xF0. The corner turn interpret these as (0+0j), (0+1j,) ...  (0+15j), (1+0j), ... (15+15j)
        '4bit_real_a':        (13, lambda self, a: np.full((self.NB//2, 2), (a, 0)).ravel() << (self.Nbits - 4)),  # Generates the complex value (a+0j) in 4-bit mode. Not offset encoded.
        '4bit_complex_ab':    (14, lambda self, a, b: np.full((self.NB//2, 2), (a, b)).ravel() << (self.Nbits - 4)),  # Generates the complex value (a+jb) in 4-bit mode. Not offset encoded.
        }

    buffer_cache = None

    def __init__(self, fpga_instance, base_address, instance_number):
        super().__init__(fpga_instance, base_address, instance_number)
        self.SAMPLES_PER_FRAME = self.NS = self.fpga.ADC_SAMPLES_PER_FRAME
        self.BYTES_PER_FRAME = self.NB = self.fpga.ADC_BYTES_PER_FRAME
        self.BYTES_PER_SAMPLE = self.BPS = self.fpga.ADC_BYTES_PER_SAMPLE
        self.Nbits  = self.fpga.ADC_BITS_PER_SAMPLE
        self.Nvalues = 1 << self.Nbits
        # self.BUFFER_SIZE = self.BYTES_PER_FRAME  # bytes
        self.FRAME_SIZE = self.BYTES_PER_FRAME  # bytes
        self.PAGE_SIZE = 512 # number of bytes accessible in one RAM page
        self.N_PAGES = self.BYTES_PER_FRAME //  self.PAGE_SIZE # number of pages

        # Determine the sample numpy storage type and how many bits to left-shift when storing in the buffer
        if self.BYTES_PER_SAMPLE not in(1 , 2):
            raise RuntimeError(f"Only ADC data with 1 or 2 bytes/samples (1-16 bits) is supported. Current value is {self.BYTES_PER_SAMPLE} bytes/sample  ")

        self.dtype = np.dtype(f'>u{self.BYTES_PER_SAMPLE}') # storage format, either dtype 'u1' or 'u2' (MSB is at lower byte address = big endian)
        self.lshift = self.dtype.itemsize*8 - self.fpga.ADC_BITS_PER_SAMPLE

        # Prevent accidental addition of attributes (if, for example, a value is assigned to a wrongly-spelled property)
        self._lock()

    def reset(self):
        """ Resets the function generator"""
        self.pulse_bit('RESET')

    def reset_noise(self):
        """Resets the seed of the noise generator and the output to 0"""
        self.pulse_bit('RST_LFSR')

    def set_data_source(self, source_name, data=None, seed=None, **kwargs):
        """
        Selects the type of data outputed by the function generator: ADC
        signal, noise generator, frame counters, predetermined or user-provided waveform.

        If the noise generator is selected, the seed can be specified as as 15-bit value in ``seed``.

        If ``data`` is specified, its values are written in the buffer.

        You may need to sync after changing the data source between the 'adc'
        and the other internally-generated sources as packet transmission
        might be interrupted and might confuse the downstream logic (FFT,
        crossbars, packet aligner etc.)
        """

        data_sources = self.DATA_SOURCE_NAMES.keys()
        function_names = self.FUNCTION_NAMES.keys()

        if source_name in function_names:
            self.set_function(source_name, **kwargs)  # set the buffer with desired waveform
            source_name = 'buffer'
        elif source_name not in data_sources:
            raise ValueError(f"Invalid data source or function name '{source_name}'. "
                             f"Valid values are {', '.join(list(data_sources) + list(function_names))}")

        if seed is not None:
            self.BYTE_A = seed & 0xff
            self.BYTE_B = (seed >> 8) & 0xff | 0x80  # Set bit 7 to indicate unknown waveform

        if data is not None:
            self.set_function('arb', data=data)

        self.FUNCTION = self.DATA_SOURCE_NAMES[source_name]

    def get_data_source(self):
        """
        Gets the data source currently selected by the the SOURCE selector.
        """
        data_source_number = self.FUNCTION  # make sure we read this only once
        return [key for (key, value) in self.DATA_SOURCE_NAMES.items() if value == data_source_number][0]

    def set_function(self, function_name, verbose=False, **kwargs):
        """
        Sets the waveform buffer with a predetermined waveform. It is recommended to use set_data_source() instead.

        Keyword arguments are passed directly to the function that generate
        the buffer data. The argument 'a' and 'b' can be specified for
        waveforms that require them. ``data`` is used to specify an arbitrary
        waveform as 2048 bytes .
        """
        if function_name not in self.FUNCTION_NAMES:
            raise RuntimeError("Invalid function name. Valid ones are '%s'" % ', '.join(self.FUNCTION_NAMES.keys()))
        (fn_number, buffer_gen) = self.FUNCTION_NAMES[function_name]
        function_args = ', '.join('%s=%.30r' % (arg, val) for (arg, val) in kwargs.items())
        buffer_info = f'{function_name}({function_args})'
        if verbose:
            print(f'*** Setting function to {buffer_info}')
        self.set_buffer(buffer_gen(self=self, **kwargs), function_number=fn_number, info=buffer_info, verbose=verbose)

    def get_function(self):
        """
        Return the name of the current waveform generated by the function generator.
        """
        (fn_number, info, crc) = self.get_buffer_info()
        fn_names = [key for (key, (number, _)) in self.FUNCTION_NAMES.items() if number == fn_number]
        if not fn_names:
            return 'Unknown'
        else:
            return fn_names[0]

    def set_ram_page(self, page):
        """ Sets the RAM page number

        Parameters:
            page (int): page to access. Must be <self.N_PAGES
        """
        if page >= self.N_PAGES:
            raise ValueError(f'Invalid page number. There are {self.N_PAGES} in this configuration')
        self.RAM_PAGE_LSB = page & 0b111
        self.RAM_PAGE_MSB = (page >> 3) & 0b1111

    def set_buffer(self, data, function_number=0, info='Arbitrary data', verbose=False):
        """ Sets the buffer contents to be used for functions that uses it.

        Parameters:

            data: Data to write in the waveform buffer.

               If `data` is an numpy array or any kind of iterable (list, tuple, generator etc.)
               whose elements that can be converted to integers, it must be `self.NS` samples long,
               and the integers it contains will be converted to the width of the ADC samples and
               left-aligned. Overflows are not detected; instead, values will wrap around.

               If 'data' is a bytestring or bytearray, it must be `self.NB` bytes long and will be
               written directly in the waveform buffer without any conversion.

               if `data` is None, no action is taken.

            function_number: Value  (0-255) to store along with the data to identify the buffer
                contents. It has no impact on the generated waveforms.

            info (str): *deprecated, not used* String that was originally stored in the FPGA to
                convey more information on the waveform that was in the buffer.

            verbose (int): Verbosity level

        """
        if data is None:
            return

        if isinstance(data, (bytes, bytearray)):
            pass  # use buffer as is.
        else:
            # make sure the data fits in the number of bits per sample for this platform as a signed or unsigned value
            if any(data < -2**(self.fpga.ADC_BITS_PER_SAMPLE-1)) or any (data > 2**(self.fpga.ADC_BITS_PER_SAMPLE)-1):
                self.logger.warning(f'{self!r}: Some sample values to be written to the FUNCGEN buffer exceed a signed or unsigned value range. Only the lower {self.fpga.ADC_BITS_PER_SAMPLE}) bits will be stored')
            if isinstance(data, np.ndarray):
                data = ((data.astype(int) << self.lshift)).astype(self.dtype).tobytes()  # convert to dtype *after* shift otherwise we lose type and endianness
            else:
                data = (np.fromiter(data, int) << self.lshift).astype(self.dtype).tobytes()
        # data = data.tobytes()
        # print(len(data), data[:100].hex(':'))


        if len(data) != self.NB:
            raise ValueError(f'Data must represent {self.NS} samples ({self.NB} bytes)')

        if self.buffer_cache is None:
            self.buffer_cache = bytearray(self.NB)
        # Write the data, page by page
        for page in range(self.N_PAGES):
            page_slice = slice(page * self.PAGE_SIZE, (page + 1) * self.PAGE_SIZE)
            page_data = data[page_slice]
            self.set_ram_page(page)
            self.write_ram(0, page_data)
            if verbose:
                print(f'page={page}, slice={page_slice}')
            self.buffer_cache[page_slice] = page_data

        # Store info on the buffer contents
        self.FUNCTION_NUMBER = function_number
        # self.RAM_PAGE = 4
        # self.write_ram(0, function_number)
        # self.write_ram(1, info.encode() + b'\x00')

    def get_buffer(self, use_cache=True):

        if use_cache and self.buffer_cache is not None:
            return self.buffer_cache
        data = bytearray(self.NB)
        for page in range(self.N_PAGES):
            self.set_ram_page(page)
            data[page * self.PAGE_SIZE: (page + 1) * self.PAGE_SIZE] = self.read_ram(0, length=self.PAGE_SIZE, type=bytearray)
        return data

    def get_buffer_info(self):
        # self.RAM_PAGE = 4
        # data = self.read_ram(0, length=512)
        # fn_number = data[0]
        # data_str = data[1:].tostring()
        # info = data_str[:data_str.index(chr(0))]
        fn_number = self.FUNCTION_NUMBER
        fn_names = [name for name, (n, _) in self.FUNCTION_NAMES.items() if n==fn_number]
        fn_name = fn_names[0] if len(fn_name) == 1 else 'Unknown'
        info = f'Function {fn_number}: {fn_name}'
        return (fn_number, info, None)  # Fn number, info string, CRC32

    def get_sim_output(self, adc_input=None, source=None, number_of_frames=4):
        """
        Return the simulated output of this module.

        Parameters:
            adc_input:  is a (adc_flags, adc_dat) tuple containing:

                - adc_flags: Numpy array of (Nframes x 512) integers values
                    indicating overflow condition for each sample of each word in bits
                    3:0. Bit 3 is for earliest sample of the word.

                - adc_data: Numpy array of (Nframes x 512) Big endian 64-bit words
                    (dtype='>u4') contained the adc samples packed in words. Bits
                    31-24 if for sample 0, bits 23-15 bit sample 1 etc.

            source:

            number_of_frames:


        Returns:
            tuple: A tuple of two 512 elements vector ``(flags, data)`` where:

                - flags:

                    - Bit 0 : Adc overflow flag for the word (set to 1 if any of the four samples in the word has overflown).
                    - Bits 1-3: '0'.
                - data: Array of big-endian 64-bit words containing the data.
        """
        if self.RESET:
            raise RuntimeError('Module is in reset')

        if source is None:
            source = self.get_data_source()

        if source == 'adc':
            if adc_input is None:
                raise RuntimeError('Need to supply ADC input vector')
            (adc_flags, adc_data) = adc_input
            cumulative_adc_flags = np.cumsum(adc_flags.astype(bool), axis=-1).astype(bool)
            flags = (cumulative_adc_flags << 0).astype(np.int8)
            return (flags, adc_data)
        elif source == 'noise':
            flags = np.zeros((number_of_frames, self.FRAME_SIZE), np.int8)
            data = np.tile(
                np.random.random_integers(-128, 127, size=self.FRAME_SIZE).astype(np.uint8).view('>u4'),
                (number_of_frames, 1))
            return (flags, data)
        elif source == 'buffer':
            flags = np.zeros((number_of_frames, self.FRAME_SIZE), np.int8)
            data = np.tile(self.get_buffer(use_cache=True).view('>u4'), (number_of_frames, 1))
            return (flags, data)
        else:
            raise RuntimeError('Unknown or unsupported data source')

    def init(self):
        """ Initializes the function generator """
        if self.fpga._NUMBER_OF_FMC_SLOTS and not self.fpga.is_fmc_present_for_channel(self.instance_number):
            # use the function generator if there are FMC slots in the system but the ADC is not present
            self.set_data_source('buffer')
            self.set_function('ramp')
        else:
            self.set_data_source('adc')  # use the ADC data

    def status(self):
        """ Displays the status of the function generator module """
        print('-------------- CHAN[%i].FUNCGEN STATUS --------------' % self.instance_number)
        print(' Function number: %i' % self.FUNCTION)
        print(' Ramp counter status:')
        print('    RAMP_CTR: %i' % self.RAMP_CTR)
