----------------------------------------------------------------------------------
-- Company: McGill University
-- Engineer: JF Cliche
--
-- Create Date:    03:00:14 03/14/2011
-- Design Name:
-- Module Name:    Clocks - Behavioral
-- Project Name:
-- Target Devices:
-- Tool versions:
-- Description: chFPGA system clock generation.
--   Transated from the Verilog version provided with the SP605 demo app.
--
-- Dependencies:
--
-- Revision:
-- 110314 JFC - File Created from verilog version
-- 2012-01-30 JFC: Added unbuffered MMCM CLK200 to drive the BUFGMUX. This is done in the context of KC705 implementation where the direct CLK200 BUFG cannot drive the BUFGMUX because it is not in the same region. In this case, the MMCM instantiated here has to be put in the same half as the BUFGMUX, and its output can directly drive the BUFGMUX
-- Additional Comments:
--
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

library UNISIM;
use UNISIM.VComponents.all;

use work.ip_package.all;

entity clocks is
	generic (
		CLOCK_INPUT: string --! Either "SYSCLK" or "SFP125"
	);
	PORT (
		-- Clock input
		sysclk_p : IN std_logic := '0'; --! Differential 200 MHz clock input from the on-board oscillator
		sysclk_n : IN std_logic := '1';

		sfp_refclk_p: in std_logic;
		sfp_refclk_n: in std_logic;

		-- Resets
		rst_in : IN std_logic; --! Active high external reset line input
		clk125_reset_out : out std_logic;
		clk200_reset_out : out std_logic;
		clk20_reset_out : out std_logic;
		clk20_90_reset_out : out std_logic;
		clk20_180_reset_out : out std_logic;

		-- Direct clock outputs
		sfp_refclk : out std_logic; --! Unbuffered SFP reference clock (No MMCM)

		-- MMCM-generated clocks
		CLK20 : OUT std_logic;
		clk20_180 : OUT std_logic;
		clk20_90: OUT std_logic;
		CLK125 : OUT std_logic;
		CLK200 : OUT std_logic
		);
end clocks;

architecture IMPL of clocks is

	signal SYSCLK_BUF: STD_LOGIC; --! External 200 MHz buffered by the differential receiver BUFGDS
	signal SYSCLK: STD_LOGIC; --! External 200 MHz clock buffered by BUFG
	signal CLK200_MMCM_NOBUF_INT: STD_LOGIC;
	signal CLK125_NOBUF: STD_LOGIC;
	signal clk20_180_NOBUF: STD_LOGIC;
	signal clk20_90_NOBUF: STD_LOGIC;
	signal CLK20_NOBUF: STD_LOGIC;

	signal sfp_refclk_nobuf: std_logic;
	signal sfp_refclk_int: std_logic;

	signal CLK_FB_OUT: STD_LOGIC;
	signal CLK_FB_IN: STD_LOGIC;

	signal LOCKED: STD_LOGIC;
	signal CLK_CTR: UNSIGNED(3 downto 0) :=X"F";

	signal async_reset: std_logic;

	-- Internal clock signals (fully buffered and ready to export)
	signal clk200_int, clk125_int, clk20_int, clk20_90_int, clk20_180_int : STD_LOGIC;

	--! Preserve the clock names so they can be used directly in the constraint files
	attribute dont_touch : string;
	attribute dont_touch of CLK200_MMCM_NOBUF_INT : signal is "true";
	attribute dont_touch of CLK125_NOBUF : signal is "true";
	attribute dont_touch of CLK20_NOBUF : signal is "true";
	attribute dont_touch of clk20_90_NOBUF : signal is "true";

begin

--! Instantiate BUFG that drives the 200 MHz clock generated by the MMCM
CLK200MMCM_BUFG : BUFG port map (
	I => CLK200_MMCM_NOBUF_INT, -- Clock buffer input
	O => clk200_int  -- Clock buffer output
);

--! Instantiate BUFG that drives the 125 MHz clock generated by the MMCM
CLK125_BUFG : BUFG port map (
	I => CLK125_NOBUF, -- Clock buffer input
	O => clk125_int -- Clock buffer output
);

--! Instantiate BUFG that drives the correlator clock generated by the MMCM
clk20_180_bufg_BUFG : BUFG port map (
	I => clk20_180_NOBUF, -- Clock buffer input
	O => clk20_180_int -- Clock buffer output
);

--! Instantiate BUFG that drives the 25 MHz clock generated by the MMCM
CLK20_BUFG : BUFG port map (
	I => CLK20_NOBUF, -- Clock buffer input
	O => clk20_int -- Clock buffer output
);

--! Instantiate BUFG that drives the system monitor clock generated by the MMCM
clk20_90_BUFG : BUFG port map (
	I => clk20_90_NOBUF, -- Clock buffer input
	O => clk20_90_int -- Clock buffer output
);

--! Instantiate BUFG that is in the feedback path. This ensures that the clock outputs after the BUFGs are aligned with the MMCM clock input
CLKFB_BUFG : BUFG port map (
	I => CLK_FB_OUT, -- Clock buffer input
	O => CLK_FB_IN -- Clock buffer output
);

use200: if CLOCK_INPUT="SYSCLK" generate

	ibufgds0 : ibufgds
	generic map(
		diff_term => TRUE
	)
	port map (
		i=>sysclk_p,
		ib=>sysclk_n,
		o=>sysclk_buf
	);

	--! Instantiate BUFG that drives the 200 MHz clock taken directly from the external oscillator input
	clk200_bufg : BUFG port map (
		I => sysclk_buf, -- Clock buffer input
		O => sysclk -- Clock buffer output
	);

	--! Instantiate the MMCM that generates other system clocks based on
	--! the external 200 MHz. The core does not instantiate an input BUFG
	--! as we already have one to drive logic directly from the clock with
	--! minimal jitter (good for 10 MHz reference generation, which
	--! requires very low jitter)
	--! The core does not instantiate BUFGs at the outputs of the MMCM.
	--! We do it manually above so we can give significant clock-related
	--! names the BUFG instances, which facilitates design analysis and
	--! constraining.

	mmcm_adv_inst : MMCME2_ADV
		generic map(
			BANDWIDTH            => "HIGH",
			CLKOUT4_CASCADE      => FALSE,
			COMPENSATION         => "ZHOLD",
			STARTUP_WAIT         => FALSE,
			DIVCLK_DIVIDE        => 1, -- 200 MHz PFD
			CLKFBOUT_MULT_F      => 5.000, -- 1 GHz VCO
			CLKFBOUT_PHASE       => 0.000,
			CLKFBOUT_USE_FINE_PS => FALSE,
			CLKOUT0_DIVIDE_F     => 5.000, -- 200 MHz
			CLKOUT0_PHASE        => 0.000,
			CLKOUT0_DUTY_CYCLE   => 0.500,
			CLKOUT0_USE_FINE_PS  => FALSE,
			CLKOUT1_DIVIDE       => 8, -- 125 MHz
			CLKOUT1_PHASE        => 0.000,
			CLKOUT1_DUTY_CYCLE   => 0.500,
			CLKOUT1_USE_FINE_PS  => FALSE,
			CLKOUT2_DIVIDE       => 50, -- 20 MHz 180 deg
			CLKOUT2_PHASE        => 180.000,
			CLKOUT2_DUTY_CYCLE   => 0.500,
			CLKOUT2_USE_FINE_PS  => FALSE,
			CLKOUT3_DIVIDE       => 50, -- 20 MHz 0 deg
			CLKOUT3_PHASE        => 0.000,
			CLKOUT3_DUTY_CYCLE   => 0.500,
			CLKOUT3_USE_FINE_PS  => FALSE,
			CLKOUT4_DIVIDE       => 50, -- 20 MHz 90 deg
			CLKOUT4_PHASE        => 90.000,
			CLKOUT4_DUTY_CYCLE   => 0.500,
			CLKOUT4_USE_FINE_PS  => FALSE,
			CLKIN1_PERIOD        => 5.0,
			REF_JITTER1          => 0.010
		) port map (
			-- Output clocks
			CLKFBOUT            => CLK_FB_OUT,
			CLKOUT0             => CLK200_MMCM_NOBUF_INT,
			CLKOUT1             => CLK125_NOBUF,
			CLKOUT2             => clk20_180_NOBUF,
			CLKOUT3             => CLK20_NOBUF,
			CLKOUT4             => clk20_90_NOBUF,
			-- Input clock control
			CLKFBIN             => CLK_FB_IN,
			CLKIN1              => sysclk,
			CLKIN2              => '0',
			-- Tied to always select the primary input clock
			CLKINSEL            => '1',
			-- Ports for dynamic reconfiguration
			DADDR               => (others => '0'),
			DCLK                => '0',
			DEN                 => '0',
			DI                  => (others => '0'),
			DO                  => open,
			DRDY                => open,
			DWE                 => '0',
			-- Ports for dynamic phase shift
			PSCLK               => '0',
			PSEN                => '0',
			PSINCDEC            => '0',
			PSDONE              => open,
			-- Other control and status signals
			LOCKED              => LOCKED,
			CLKINSTOPPED        => open,
			CLKFBSTOPPED        => open,
			PWRDWN              => '0',
			RST                 => RST_IN
		);
end generate;

use_sfp125: if CLOCK_INPUT="SFP125" generate

	ibufds_gtrefclk : IBUFDS_GTE2 port map (
		I     => sfp_refclk_p,
		IB    => sfp_refclk_n,
		CEB   => '0',
		O     => sfp_refclk_nobuf,
		ODIV2 => open
	);

	bufg_gtrefclk : BUFG port map (
		I => sfp_refclk_nobuf,
		O => sfp_refclk_int
	);

	sfp_refclk <= sfp_refclk_nobuf;

	-- The PLL takes the 125 MHz sfp_refclk and generates the various
	-- clocks needed by the system (125 MHz, 200 MHz, 25 MHz)
	-- VCO_Freq = 1 GHz (must be 600-1440 MHz).
	mmcm0 : MMCME2_ADV
		generic map(
			BANDWIDTH            => "OPTIMIZED",
			CLKOUT4_CASCADE      => FALSE,
			COMPENSATION         => "ZHOLD",
			STARTUP_WAIT         => FALSE,
			DIVCLK_DIVIDE        => 1, -- 125 MHz PFD
			CLKFBOUT_MULT_F      => 8.000, -- 1 GHz VCO
			CLKFBOUT_PHASE       => 0.000,
			CLKFBOUT_USE_FINE_PS => FALSE,
			CLKOUT0_DIVIDE_F     => 5.000, -- 200 MHz
			CLKOUT0_PHASE        => 0.000,
			CLKOUT0_DUTY_CYCLE   => 0.500,
			CLKOUT0_USE_FINE_PS  => FALSE,
			CLKOUT1_DIVIDE       => 8, -- 125 MHz
			CLKOUT1_PHASE        => 0.000,
			CLKOUT1_DUTY_CYCLE   => 0.500,
			CLKOUT1_USE_FINE_PS  => FALSE,
			CLKOUT2_DIVIDE       => 50, -- 20 MHz 180 deg
			CLKOUT2_PHASE        => 180.000,
			CLKOUT2_DUTY_CYCLE   => 0.500,
			CLKOUT2_USE_FINE_PS  => FALSE,
			CLKOUT3_DIVIDE       => 50, -- 20 MHz 0 deg
			CLKOUT3_PHASE        => 0.000,
			CLKOUT3_DUTY_CYCLE   => 0.500,
			CLKOUT3_USE_FINE_PS  => FALSE,
			CLKOUT4_DIVIDE       => 50, -- 20 MHz 90 deg
			CLKOUT4_PHASE        => 90.000,
			CLKOUT4_DUTY_CYCLE   => 0.500,
			CLKOUT4_USE_FINE_PS  => FALSE,
			CLKIN1_PERIOD        => 8.0, -- 125 MHz
			REF_JITTER1          => 0.010
		) port map (
			-- Output clocks
			CLKFBOUT     => CLK_FB_OUT,
			CLKOUT0             => CLK200_MMCM_NOBUF_INT,
			CLKOUT1             => CLK125_NOBUF,
			CLKOUT2             => clk20_180_NOBUF,
			CLKOUT3             => CLK20_NOBUF,
			CLKOUT4             => clk20_90_NOBUF,
			-- Input clock control
			CLKFBIN      => CLK_FB_IN,
			CLKIN1       => sfp_refclk_int,
			CLKIN2       => '0',
			-- Tied to always select the primary input clock
			CLKINSEL     => '1',
			-- Ports for dynamic reconfiguration
			DADDR        => (others => '0'),
			DCLK         => '0',
			DEN          => '0',
			DI           => (others => '0'),
			DO           => open,
			DRDY         => open,
			DWE          => '0',
			-- Ports for dynamic phase shift
			PSCLK        => '0',
			PSEN         => '0',
			PSINCDEC     => '0',
			PSDONE       => open,
			-- Other control and status signals
			LOCKED       => LOCKED,
			CLKINSTOPPED => open,
			CLKFBSTOPPED => open,
			PWRDWN       => '0',
			RST          => RST_IN
		);
end generate;

--! reset process: Keep the reset line active until the PLL is locked for a few cycles.
async_reset <= rst_in or (not locked);
clk200_reset : entity work.sync_reset port map (
	clk => clk200_int ,
	async_reset => async_reset,
	reset_out => clk200_reset_out
);


clk125_reset : entity work.sync_reset port map (
	clk => clk125_int,
	async_reset => async_reset,
	reset_out => clk125_reset_out
);

clk20_reset0 : entity work.sync_reset port map (
	clk => clk20_int,
	async_reset => async_reset,
	reset_out => clk20_reset_out
);
clk20_reset90 : entity work.sync_reset port map (
	clk => clk20_90_int,
	async_reset => async_reset,
	reset_out => clk20_90_reset_out
);
clk20_reset180 : entity work.sync_reset port map (
	clk => clk20_180_int,
	async_reset => async_reset,
	reset_out => clk20_180_reset_out
);

clk200 <= clk200_int ; -- Use mmcm clock output so we are in phase with the 20 MHz adc/dac clock.
clk125 <= clk125_int;
clk20 <= clk20_int;
clk20_90 <= clk20_90_int;
clk20_180 <= clk20_180_int;

end IMPL;
