----------------------------------------------------------------------------------
--! @file
--! @brief Core iceboard firmware extected to be present on every IceBoard application
-- Company: McGill University
-- Engineers: JF Cliche (JFC Inc) & Graeme Smecher (Three-Speed Logic, Inc)
--
-- Create Date:    2014-12-15
-- Design Name:    ICE development environment
-- Module Name:    icecore
-- Project Name:   Generic
-- Target Devices:  Kintex 7 on IceBoard (McGill Model MGK7MB)
-- Tool versions:  Vivado 2014.4
---  LIBRARY DECLARATIONS ----------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_misc.all; -- for or_reduce()

library UNISIM;
use UNISIM.VComponents.all;

use work.icecore_package.all;

entity icecore is
	generic (
		MASTER_CLOCK_SOURCE: string ; -- either "SYSCLK" or "CLK125"
		APPLICATION_COOKIE: std_logic_vector(31 downto 0) := x"00000002";
		APPLICATION_FLAGS: std_logic_vector(31 downto 0) := X"30000000";
		IMPLEMENT_TIMESTAMP: boolean := TRUE;
		SIM: BOOLEAN:= FALSE --! Indicates this is running as a simulation. Used to accelerate simulations
	);
	port (
		-- ARM <-> FPGA SPI port
		arm_spi_sck: in std_logic;
		arm_spi_miso: out std_logic;
		arm_spi_mosi: in std_logic;
		arm_spi_cs_n: in std_logic;

		-- Reset line
		cpu_reset: in STD_LOGIC;

		irig_bp, irig_sma: in std_logic := '0';
		irigb_timestamp: out irigb;

		-- 200 MHz system clock
		sysclk_p: in std_logic:='0'; --!  200 MHz differential (lvds) clock generated by a crystal oscillator on the board
		sysclk_n: in std_logic:='1';

		sync_1v0: out std_logic;
		sync_1v8: out std_logic;
		sync_1v0_gtx: out std_logic;
		sync_5v0: out std_logic;
		sync_1v2: out std_logic;
		sync_vadj: out std_logic;
		sync_1v5: out std_logic;
		sync_3v3: out std_logic;
		sync_12v0: out std_logic;

		------------------------------------
		--  ARM PCIe / SFP (Gbit Ethernet)
		------------------------------------

		sfp_clk125_p: in std_logic :='0'; --! sfp reference clock, generated on-board using a high quality oscillator and used to synchronize the mgt used to communicate to the sfp.
		sfp_clk125_n: in std_logic :='1';
		pcie_sfp_tx_p: out std_logic ; --! serialized data from the fpga mgt to the sfp
		pcie_sfp_tx_n: out std_logic;
		pcie_sfp_rx_p: in std_logic:='0'; --! serialized data from the sfp to the fpga mgt
		pcie_sfp_rx_n: in std_logic:='1';

		-- IO control registers
		io_ctrl0_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl0_wr: out std_logic_vector(31 downto 0);
		io_ctrl1_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl1_wr: out std_logic_vector(31 downto 0);
		io_ctrl2_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl2_wr: out std_logic_vector(31 downto 0);
		io_ctrl3_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl3_wr: out std_logic_vector(31 downto 0);

		-- Basic FMC signals
		fmca_mezz_buck_sync: out std_logic; -- 1 MHz buck converter synchronization that can be used for mezzanines if needed.
		fmcb_mezz_buck_sync: out std_logic;

		clk200: out std_logic; -- 200 MHz clock output to be used by the top-level I/O interface blocks
		clk125: out std_logic -- 125 MHz clock output to be used by the top-level I/O interface blocks
	);
end icecore;

architecture IMPL of icecore is

	-- Attributes
	attribute equivalent_register_removal: string;
	attribute keep:string;
	attribute shreg_extract: string;

	-- Clocks & global reset
	signal clk125_int, clk200_int, clk20, clk20_90, clk20_180: std_logic;
	signal pcie_sfp_refclk: std_logic; --! 125 MHz generated from the PHY reference clock
	signal reset_125, reset_200, reset_20, reset_20_90, reset_20_180: std_logic; -- Internal RESET after the clocks are stable

	-- Control bus
	signal spi_addr, spi_rdat, spi_wdat: std_logic_vector(31 downto 0) := (others => '0');
	signal spi_rreq, spi_rack, spi_wreq, spi_wack: std_logic := '0';

	constant CORE_REG_BUS_NUMBER: integer := 0;
	constant IRIG_BUS_NUMBER: integer := 1;
	constant USER_BUS_NUMBER: integer := 2;
	constant NUMBER_OF_BUSES: integer := 3;

	signal ctl_addr: slv32_array(0 to NUMBER_OF_BUSES-1);
	signal ctl_wdat: slv32_array(0 to NUMBER_OF_BUSES-1);
	signal ctl_rdat: slv32_array(0 to NUMBER_OF_BUSES-1) := (others=>(others=>'0')); -- initialized in case a slave is not connected
	signal ctl_rreq, ctl_rack, ctl_wreq, ctl_wack: std_logic_vector(0 to NUMBER_OF_BUSES-1) := (others=>'0');

	signal addr: unsigned(18 downto 0) := (others => '0');
	signal addr_dly: unsigned(18 downto 0) := (others => '0');
	signal din_dly: std_logic_vector(31 downto 0) := (others => '0');


	signal firmware_crc32: std_logic_vector(31 downto 0);
	signal firmware_timestamp: std_logic_vector(31 downto 0);
	signal firmware_timestamp_valid: std_logic;

	signal dna_clk: std_logic;
	signal dna_dout: std_logic;
	signal dna_read: std_logic :='1'; -- First clock is a read
	signal dna_shift: std_logic := '1'; -- Will start shifting as soon as read is disabled
	signal dna_ctr: unsigned(5 downto 0) := to_unsigned(57-1, 6); -- Will shift 57 times
	signal fpga_serial_number: std_logic_vector(56 downto 0) := (others=>'0'); -- Need to initialize because we do not shift all the 64 bits

	signal fpga_ip_address: std_logic_vector(31 downto 0) := X"0A0A0A0B";
	signal fpga_ip_port: std_logic_vector(15 downto 0) := X"A028"; -- 41000
	signal fpga_mac_address: std_logic_vector(47 downto 0) := X"123456789ABC";

	constant NUMBER_OF_CORE_REGISTERS: integer := 10;
	signal core_reg_wr_value : slv32_array(0 to NUMBER_OF_CORE_REGISTERS-1);
	signal core_reg_rd_value : slv32_array(0 to NUMBER_OF_CORE_REGISTERS-1);
	constant core_reg_default_values : slv32_array(0 to NUMBER_OF_CORE_REGISTERS-1) := (
		7 => X"12345678",
		8 => X"9ABC_A028",
		9 => X"0A0A0A0B",
		others => X"00000000" );


	constant NUMBER_OF_USER_REGS: integer := 10;
	signal user_reg_wr_value : slv32_array(0 to NUMBER_OF_USER_REGS-1);
	signal user_reg_rd_value : slv32_array(0 to NUMBER_OF_USER_REGS-1);

begin

-------------------------
-- Core Register assignments
-------------------------

-- Register Read values
core_reg_rd_value(0) <= x"beefface"; -- (Read only) Core firmware cookie
core_reg_rd_value(1) <= APPLICATION_COOKIE; -- (Read only) Application firmware cookie
core_reg_rd_value(2) <= APPLICATION_FLAGS; -- (Read only) Application Flags: Kintex 7
core_reg_rd_value(3) <= firmware_crc32; -- (Read/Write with readback) Firmware CRC32, computed by the host application and stored here for future reference
core_reg_rd_value(4) <= firmware_timestamp; -- (Read only) Firmware timestamp, taken from the USER_ACCESS data filled in when the bitstream file was generated
core_reg_rd_value(5) <= fpga_serial_number(31 downto 0); -- (Read only)
core_reg_rd_value(6) <= "0000000" & fpga_serial_number(56 downto 32); -- (Read only)
core_reg_rd_value(7) <= fpga_mac_address(31 downto 0); -- (Read/Write with readback)
core_reg_rd_value(8) <= fpga_mac_address(47 downto 32) & fpga_ip_port; -- (Read/Write with readback)
core_reg_rd_value(9) <= fpga_ip_address; -- (Read/Write with readback)
-- core_reg_rd_value(7 to 9) <= core_reg_wr_value(7 to 9); -- Readback FPGA  Ethernet parameters

-- Register write values
firmware_crc32                 <= core_reg_wr_value(3);
fpga_mac_address(31 downto 0)  <= core_reg_wr_value(7);
fpga_mac_address(47 downto 32) <= core_reg_wr_value(8)(31 downto 16);
fpga_ip_port                   <= core_reg_wr_value(8)(15 downto 0);
fpga_ip_address                <= core_reg_wr_value(9);


	-------------------------------------------------------------------
	-- Instantiate System clocks
	-------------------------------------------------------------------

	--! Instantiate the system clock generator
	clk0: entity work.clocks
	generic map(
		CLOCK_INPUT => MASTER_CLOCK_SOURCE -- either "SYSCLK", "SFP125"
	)
	port map (
		-- System clock input
		-- sysclk_p            => sysclk_p, -- Differential 200 MHz clock
		-- sysclk_n            => sysclk_n,
		sfp_refclk_p        => sfp_clk125_p, -- Differential 125 MHz clock on a GTX clock input
		sfp_refclk_n        => sfp_clk125_n,

		sfp_refclk          => pcie_sfp_refclk, -- unbuffered SFP reference clock output

		-- MMCM-generated clocks
		clk20               => clk20,
		clk20_90            => clk20_90,
		clk20_180           => clk20_180,
		clk125              => clk125_int,
		clk200              => clk200_int,

		-- Resets
		rst_in              => cpu_reset,
		clk125_reset_out    => reset_125,
		clk200_reset_out    => reset_200,
		clk20_reset_out     => reset_20,
		clk20_90_reset_out  => reset_20_90,
		clk20_180_reset_out => reset_20_180
	);

	clk200 <= clk200_int;
	clk125 <= clk125_int;

	buck_sync0: entity work.buck_sync
		port map (
			clk_200mhz   => clk200_int,

			sync_fmca    => fmca_mezz_buck_sync,
			sync_fmcb    => fmcb_mezz_buck_sync,

			sync_1v0     => sync_1v0,
			sync_1v8     => sync_1v8,
			sync_1v0_gtx => sync_1v0_gtx,
			sync_5v0     => sync_5v0,
			sync_1v2     => sync_1v2,
			sync_vadj    => sync_vadj,
			sync_1v5     => sync_1v5,
			sync_3v3     => sync_3v3,
			sync_12v0    => sync_12v0
		);

	---------------------------------------------------------------------
	-- ARM <-> FPGA serial interface
	---------------------------------------------------------------------
	-- Is used to communicate memory-mapped read/writes commands from the ARM to the FPGA and return the data to the ARM

	arm_spi0: entity work.arm_spi port map (
		-- SPI interface
		sck => arm_spi_sck,
		miso => arm_spi_miso,
		mosi => arm_spi_mosi,
		cs_n => arm_spi_cs_n,

		-- Master bus interface
		m_addr => spi_addr,
		m_rdat => spi_rdat,
		m_wdat => spi_wdat,
		m_rreq => spi_rreq,
		m_rack => spi_rack,
		m_wreq => spi_wreq,
		m_wack => spi_wack,

		clk => clk125_int,
		reset => '0' -- redundant; cs_n does the same thing

	);


	---------------------------------------------------------------------
	-- BUS interconnect
	---------------------------------------------------------------------
	-- Used to connect multiple slaves to the bus master . For now this is very primitive as there is no address-based routing.
	-- This should one day be replaced by a full-fledged AXI4 interconnect.

	bus_interconnect0: entity work.bus_interconnect
		generic map (
			NUMBER_OF_MASTER_INTERFACES => NUMBER_OF_BUSES
		)
		port map (

			-- Slave interface (from master)
			s_addr => spi_addr,
			s_wdat => spi_wdat,
			s_rdat => spi_rdat,
			s_rreq => spi_rreq,
			s_rack => spi_rack,
			s_wreq => spi_wreq,
			s_wack => spi_wack,

			-- Master interfaces (to slaves)
			m_addr => ctl_addr,
			m_wdat => ctl_rdat,
			m_rdat => ctl_wdat,
			m_rreq => ctl_rreq,
			m_rack => ctl_rack,
			m_wreq => ctl_wreq,
			m_wack => ctl_wack,

			clk => clk125_int
			);


	---------------------------------------------------------------------
	-- Core registers
	---------------------------------------------------------------------
	-- Provide basic information on the hardware and firmware

core_regs0: entity work.register_array
	generic map(
		ADDRESS_MASK => X"000000" & "------XX",
		NUMBER_OF_REGISTERS => NUMBER_OF_CORE_REGISTERS,
		DEFAULT_REGISTER_VALUES => core_reg_default_values,
		ADDRESS_WIDTH => 32,
		SIM => SIM --! Indicates this is running as a simulation. Used to accelerate simulations
	)
	port map (
		-- Control interface (*** JFC: to be replaced by an AXI4-Lite bus)
		s_addr => ctl_addr(CORE_REG_BUS_NUMBER),
		s_wdat => ctl_wdat(CORE_REG_BUS_NUMBER),
		s_rdat => ctl_rdat(CORE_REG_BUS_NUMBER),
		s_wreq => ctl_wreq(CORE_REG_BUS_NUMBER),
		s_wack => ctl_wack(CORE_REG_BUS_NUMBER),
		s_rreq => ctl_rreq(CORE_REG_BUS_NUMBER),
		s_rack => ctl_rack(CORE_REG_BUS_NUMBER),

		-- Register interface
		reg_wr_value  => core_reg_wr_value,
		reg_rd_value  => core_reg_rd_value,

		clk => clk125_int -- Clocks both control and register interface
	);



-- core_regs0: entity work.core_registers
-- 	generic map(
-- 		ADDRESS_MASK => X"000000" & "------XX", -- addr(31:8) must match 0x000000 , register word address is 6 bits, last 2 bits are ignored as addresses must be on word boundaries only
-- 		-- ADDRESS_MASK => "000000000000000000000000------XX",
-- 		APPLICATION_COOKIE => X"00000002",
-- 		APPLICATION_FLAGS => X"30000000",
-- 		SIM => FALSE --! Indicates this is running as a simulation. Used to accelerate simulations
-- 	)
-- 	port map (
-- 		-- Control interface (*** JFC: to be replaced by an AXI4-Lite bus)
-- 		addr => ctl_addr(CORE_REG_BUS_NUMBER),
-- 		din  => ctl_wdat(CORE_REG_BUS_NUMBER),
-- 		wreq => ctl_wreq(CORE_REG_BUS_NUMBER),
-- 		rreq => ctl_rreq(CORE_REG_BUS_NUMBER),
-- 		wack => ctl_wack(CORE_REG_BUS_NUMBER),
-- 		rack => ctl_rack(CORE_REG_BUS_NUMBER),
-- 		dout => ctl_rdat(CORE_REG_BUS_NUMBER),

-- 		clk  => clk125_int, -- interface clock

-- 		dna_clk => clk20 -- dna clock, <97 MHz
-- 	);

app_regs0: entity work.register_array
	generic map(
		ADDRESS_MASK => X"000001" & "------XX", -- up to 64 registers starting at 0x0000_0100
		NUMBER_OF_REGISTERS => NUMBER_OF_USER_REGS,
		DEFAULT_REGISTER_VALUES => (0 to NUMBER_OF_USER_REGS-1 => X"AAAAAAAA"),
		ADDRESS_WIDTH => 32,
		SIM => SIM --! Indicates this is running as a simulation. Used to accelerate simulations
	)
	port map (
		-- Control interface (*** JFC: to be replaced by an AXI4-Lite bus)
		s_addr => ctl_addr(USER_BUS_NUMBER),
		s_wdat => ctl_wdat(USER_BUS_NUMBER),
		s_wreq => ctl_wreq(USER_BUS_NUMBER),
		s_rreq => ctl_rreq(USER_BUS_NUMBER),
		s_wack => ctl_wack(USER_BUS_NUMBER),
		s_rdat => ctl_rdat(USER_BUS_NUMBER),
		s_rack => ctl_rack(USER_BUS_NUMBER),

		-- Register interface
		reg_wr_value  => user_reg_wr_value,
		reg_rd_value  => user_reg_rd_value,

		clk => clk125_int -- Clocks both control and register interface
	);

	---------------------------------------------------------------------
	-- IRIG-B timestamp receiver
	---------------------------------------------------------------------
	-- Timestamp decoders
	-- To be enabled later
timestamp_gen: if IMPLEMENT_TIMESTAMP=TRUE generate
	timestamp0: entity work.timestamp
		port map (
			clk        => clk125_int,
			clk_200mhz => clk200_int,

			irig_bp    => irig_bp,
			irig_sma   => irig_sma,

			ts_out           => irigb_timestamp,
			timing_reset_200 => open,
			calibration_out  => open,

			addr => unsigned(ctl_addr(IRIG_BUS_NUMBER)(4 downto 0)),
			rreq => ctl_rreq(IRIG_BUS_NUMBER),
			rack => ctl_rack(IRIG_BUS_NUMBER),
			wreq => ctl_wreq(IRIG_BUS_NUMBER),
			wack => ctl_wack(IRIG_BUS_NUMBER),
			din  => ctl_wdat(IRIG_BUS_NUMBER),
			dout => ctl_rdat(IRIG_BUS_NUMBER)
		);
end generate;



	---------------------------------------------------------------------
	-- USER ACCESS port
	---------------------------------------------------------------------
-- Accesses the timestamp (or user-defined data) that was inserted during bitstream generation.


usr_access0: USR_ACCESSE2
	port map(
		CFGCLK => open,--1-bit Configuration Clock output
		DATA => firmware_timestamp,--32-bit Configuration Data output
		DATAVALID => firmware_timestamp_valid --1-bit Active high data validoutput
		);

	---------------------------------------------------------------------
	-- DNA port
	---------------------------------------------------------------------
-- Accesses the 57-bit FPGA unique serial number
dna_clk <= clk20;

dna0 : DNA_PORT
	generic map (
		SIM_DNA_VALUE => X"000000000000000" -- Specifies a sample 57-bit DNA value for simulation
	)
	port map (
		DOUT => dna_dout, -- 1-bit output: DNA output data.
		CLK => dna_clk, -- 1-bit input: Clock input.
		DIN => '0', -- 1-bit input: User data input pin.
		READ => dna_read, -- 1-bit input: Active high load DNA, active low read input.
		SHIFT => dna_shift -- 1-bit input: Active high shift enable input.
	);

-- Process to read the DNA serial port and reconstruct the 57 bit serial number
dna_proc: process(dna_clk)
	begin
		if rising_edge(dna_clk) then
			dna_read <='0';
			if dna_read='0' and dna_shift='1' then -- when data is ready and we have not finished shifting
				fpga_serial_number <= std_logic_vector(shift_left(unsigned(fpga_serial_number), 1));
				fpga_serial_number(0) <= dna_dout;
				dna_ctr <= dna_ctr - 1;
				if dna_ctr = 0 then
					dna_shift <= '0';
				end if;
			end if;
		end if;
	end process;


	---------------------------------------------------------------------
	-- Internal ADC/System monitor
	---------------------------------------------------------------------
	-- We don't expose any ports internally; temperatures and voltages are
	-- read back using JTAG.

	U0: XADC
	generic map(
		INIT_40 => X"b000", -- temperature sensor, lots of averaging
		INIT_41 => X"2ef0", -- continuous seq, enable calibration
		INIT_42 => X"0800", -- set ADCCLK to 25 MHz (200/8)
		INIT_48 => X"4701", -- enable temperature, vccint, vccaux, vccbram, calibration
		INIT_49 => X"0000", -- disabled
		INIT_4A => X"0000", -- SEQAVG1 disabled
		INIT_4B => X"0000", -- SEQAVG2 disabled
		INIT_4C => X"0000", -- SEQINMODE0
		INIT_4D => X"0000", -- SEQINMODE1
		INIT_4E => X"0000", -- SEQACQ0
		INIT_4F => X"0000", -- SEQACQ1
		INIT_50 => X"b5ed", -- Temp upper alarm trigger 85°C
		INIT_51 => X"5999", -- Vccint upper alarm limit 1.05V
		INIT_52 => X"A147", -- Vccaux upper alarm limit 1.89V
		INIT_53 => X"dddd", -- OT upper alarm limit 125°C
		INIT_54 => X"a93a", -- Temp lower alarm reset 60°C
		INIT_55 => X"5111", -- Vccint lower alarm limit 0.95V
		INIT_56 => X"91Eb", -- Vccaux lower alarm limit 1.71V
		INIT_57 => X"ae4e", -- OT lower alarm reset 70°C
		INIT_58 => X"5999", -- VCCBRAM upper alarm limit 1.05V
		SIM_MONITOR_FILE => "design.txt"
	) port map (
		CONVST              => '0',
		CONVSTCLK           => '0',
		DADDR               => (others => '0'),
		DCLK                => clk200_int,
		DEN                 => '0',
		DI(15 downto 0)     => (others => '0'),
		DWE                 => '0',
		RESET               => '0',
		VAUXN(15 downto 0)  => (others => '0'),
		VAUXP(15 downto 0)  => (others => '0'),
		ALM                 => open,
		BUSY                => open,
		CHANNEL             => open,
		DO                  => open,
		DRDY                => open,
		EOC                 => open,
		EOS                 => open,
		JTAGBUSY            => open,
		JTAGLOCKED          => open,
		JTAGMODIFIED        => open,
		OT                  => open,
		MUXADDR             => open,
		VN                  => '0',
		VP                  => '0'
	);


end IMPL;
