----------------------------------------------------------------------------------
--! @file
--! @brief Core iceboard firmware extected to be present on every IceBoard application
-- Company: McGill University
-- Engineers: JF Cliche (JFC Inc) & Graeme Smecher (Three-Speed Logic, Inc)
--
-- Create Date:    2014-12-15
-- Design Name:    ICE development environment
-- Module Name:    icecore
-- Project Name:   Generic
-- Target Devices:  Kintex 7 on IceBoard (McGill Model MGK7MB)
-- Tool versions:  Vivado 2014.4
---  LIBRARY DECLARATIONS ----------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_misc.all; -- for or_reduce()

library UNISIM;
use UNISIM.VComponents.all;

use work.icecore_package.all;

entity icecore is
	generic (
		MASTER_CLOCK_SOURCE: string ; -- either "SYSCLK" or "CLK125"
		APPLICATION_COOKIE: std_logic_vector(31 downto 0) := x"00000002";
		APPLICATION_FLAGS: std_logic_vector(31 downto 0) := X"30000000";
		IMPLEMENT_TIMESTAMP: boolean := TRUE;
		SIM: BOOLEAN:= FALSE --! Indicates this is running as a simulation. Used to accelerate simulations
	);
	port (
		-- ARM <-> FPGA SPI port
		arm_spi_sck: in std_logic;
		arm_spi_miso: out std_logic;
		arm_spi_mosi: in std_logic;
		arm_spi_cs_n: in std_logic;

		-- Reset line
		cpu_reset: in STD_LOGIC;

		irig_bp, irig_sma: in std_logic := '0';
		irigb_timestamp: out irigb;

		-- 200 MHz system clock
		sysclk_p: in std_logic:='0'; --!  200 MHz differential (lvds) clock generated by a crystal oscillator on the board
		sysclk_n: in std_logic:='1';

		sync_1v0: out std_logic;
		sync_1v8: out std_logic;
		sync_1v0_gtx: out std_logic;
		sync_5v0: out std_logic;
		sync_1v2: out std_logic;
		sync_vadj: out std_logic;
		sync_1v5: out std_logic;
		sync_3v3: out std_logic;
		sync_12v0: out std_logic;

		------------------------------------
		--  ARM PCIe / SFP (Gbit Ethernet)
		------------------------------------

		sfp_clk125_p: in std_logic :='0'; --! sfp reference clock, generated on-board using a high quality oscillator and used to synchronize the mgt used to communicate to the sfp.
		sfp_clk125_n: in std_logic :='1';
		pcie_sfp_tx_p: out std_logic ; --! serialized data from the fpga mgt to the sfp
		pcie_sfp_tx_n: out std_logic;
		pcie_sfp_rx_p: in std_logic:='0'; --! serialized data from the sfp to the fpga mgt
		pcie_sfp_rx_n: in std_logic:='1';

		-- IO control registers
		io_ctrl0_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl0_wr: out std_logic_vector(31 downto 0);
		io_ctrl1_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl1_wr: out std_logic_vector(31 downto 0);
		io_ctrl2_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl2_wr: out std_logic_vector(31 downto 0);
		io_ctrl3_rd: in std_logic_vector(31 downto 0):=(others=>'0');
		io_ctrl3_wr: out std_logic_vector(31 downto 0);

		-- Basic FMC signals
		fmca_mezz_buck_sync: out std_logic; -- 1 MHz buck converter synchronization that can be used for mezzanines if needed.
		fmcb_mezz_buck_sync: out std_logic;

		clk200: out std_logic; -- 200 MHz clock output to be used by the top-level I/O interface blocks
		clk125: out std_logic -- 125 MHz clock output to be used by the top-level I/O interface blocks
	);
end icecore;

architecture IMPL of icecore is

	-- Attributes
	attribute equivalent_register_removal: string;
	attribute keep:string;
	attribute shreg_extract: string;

	-- Clocks & global reset
	signal clk125_int, clk200_int, clk20, clk20_90, clk20_180: std_logic;
	signal pcie_sfp_refclk: std_logic; --! 125 MHz generated from the PHY reference clock
	signal reset_125, reset_200, reset_20, reset_20_90, reset_20_180: std_logic; -- Internal RESET after the clocks are stable

	-- Control bus
	signal ctl_addr, ctl_din, ctl_dout: std_logic_vector(31 downto 0) := (others => '0');
	signal ctl_rreq, ctl_rack, ctl_wreq, ctl_wack: std_logic := '0';


	-- Define module addresses
	constant BASE_ADDR: integer := 0; -- Core Control register
	constant TS_CTL_ADDR: integer := 1;
	constant NUMBER_OF_MODULES: integer := 2;

	signal addr: unsigned(18 downto 0) := (others => '0');
	signal addr_dly: unsigned(18 downto 0) := (others => '0');
	signal din_dly: std_logic_vector(31 downto 0) := (others => '0');

	-- Bus control signals for each module, packed into arrays
	signal rreq, rack, wreq, wack: std_logic_vector(0 to NUMBER_OF_MODULES-1) := (others => '0');
	signal dout: SLV32_ARRAY_TYPE(0 to NUMBER_OF_MODULES-1) := (others=> (others=>'0'));

	signal firmware_crc32: std_logic_vector(31 downto 0);

begin

	-------------------------------------------------------------------
	-- Instantiate System clocks
	-------------------------------------------------------------------

	--! Instantiate the system clock generator
	clk0: entity work.clocks
	generic map(
		CLOCK_INPUT => MASTER_CLOCK_SOURCE -- either "SYSCLK", "SFP125"
	)
	port map (
		-- System clock input
		-- sysclk_p            => sysclk_p, -- Differential 200 MHz clock
		-- sysclk_n            => sysclk_n,
		sfp_refclk_p        => sfp_clk125_p, -- Differential 125 MHz clock on a GTX clock input
		sfp_refclk_n        => sfp_clk125_n,

		sfp_refclk          => pcie_sfp_refclk, -- unbuffered SFP reference clock output

		-- MMCM-generated clocks
		clk20               => clk20,
		clk20_90            => clk20_90,
		clk20_180           => clk20_180,
		clk125              => clk125_int,
		clk200              => clk200_int,

		-- Resets
		rst_in              => cpu_reset,
		clk125_reset_out    => reset_125,
		clk200_reset_out    => reset_200,
		clk20_reset_out     => reset_20,
		clk20_90_reset_out  => reset_20_90,
		clk20_180_reset_out => reset_20_180
	);

	clk200 <= clk200_int;
	clk125 <= clk125_int;

	buck_sync0: entity work.buck_sync
	port map (
		clk_200mhz   => clk200_int,

		sync_fmca    => fmca_mezz_buck_sync,
		sync_fmcb    => fmcb_mezz_buck_sync,

		sync_1v0     => sync_1v0,
		sync_1v8     => sync_1v8,
		sync_1v0_gtx => sync_1v0_gtx,
		sync_5v0     => sync_5v0,
		sync_1v2     => sync_1v2,
		sync_vadj    => sync_vadj,
		sync_1v5     => sync_1v5,
		sync_3v3     => sync_3v3,
		sync_12v0    => sync_12v0
	);

	---------------------------------------------------------------------
	-- ARM <-> FPGA serial interface
	---------------------------------------------------------------------
	-- Is used to communicate memory-mapped read/writes commands from the ARM to the FPGA and return the data to the ARM

	arm_spi0: entity work.arm_spi port map (
		clk => clk125_int,
		reset => '0', -- redundant; cs_n does the same thing

		din => ctl_dout,
		dout => ctl_din,
		addr => ctl_addr,
		rreq => ctl_rreq,
		rack => ctl_rack,
		wreq => ctl_wreq,
		wack => ctl_wack,

		sck => arm_spi_sck,
		miso => arm_spi_miso,
		mosi => arm_spi_mosi,
		cs_n => arm_spi_cs_n
	);

	---------------------------------------------------------------------
	-- IRIG-B timestamp receiver
	---------------------------------------------------------------------
	-- Timestamp decoders
	-- To be enabled later
timestamp_gen: if IMPLEMENT_TIMESTAMP=TRUE generate
	timestamp0: entity work.timestamp port map (
		clk        => clk125_int,
		clk_200mhz => clk200_int,

		irig_bp    => irig_bp,
		irig_sma   => irig_sma,

		ts_out           => irigb_timestamp,
		timing_reset_200 => open,
		calibration_out  => open,

		addr => addr_dly(4 downto 0),
		rreq => rreq(TS_CTL_ADDR),
		rack => rack(TS_CTL_ADDR),
		wreq => wreq(TS_CTL_ADDR),
		wack => wack(TS_CTL_ADDR),
		din  => din_dly,
		dout => dout(TS_CTL_ADDR)
	);
end generate;

	---------------------------------------------------------------------
	-- Internal ADC/System monitor
	---------------------------------------------------------------------
	-- We don't expose any ports internally; temperatures and voltages are
	-- read back using JTAG.

	U0: XADC
	generic map(
		INIT_40 => X"b000", -- temperature sensor, lots of averaging
		INIT_41 => X"2ef0", -- continuous seq, enable calibration
		INIT_42 => X"0800", -- set ADCCLK to 25 MHz (200/8)
		INIT_48 => X"4701", -- enable temperature, vccint, vccaux, vccbram, calibration
		INIT_49 => X"0000", -- disabled
		INIT_4A => X"0000", -- SEQAVG1 disabled
		INIT_4B => X"0000", -- SEQAVG2 disabled
		INIT_4C => X"0000", -- SEQINMODE0
		INIT_4D => X"0000", -- SEQINMODE1
		INIT_4E => X"0000", -- SEQACQ0
		INIT_4F => X"0000", -- SEQACQ1
		INIT_50 => X"b5ed", -- Temp upper alarm trigger 85°C
		INIT_51 => X"5999", -- Vccint upper alarm limit 1.05V
		INIT_52 => X"A147", -- Vccaux upper alarm limit 1.89V
		INIT_53 => X"dddd", -- OT upper alarm limit 125°C
		INIT_54 => X"a93a", -- Temp lower alarm reset 60°C
		INIT_55 => X"5111", -- Vccint lower alarm limit 0.95V
		INIT_56 => X"91Eb", -- Vccaux lower alarm limit 1.71V
		INIT_57 => X"ae4e", -- OT lower alarm reset 70°C
		INIT_58 => X"5999", -- VCCBRAM upper alarm limit 1.05V
		SIM_MONITOR_FILE => "design.txt"
	) port map (
		CONVST              => '0',
		CONVSTCLK           => '0',
		DADDR               => (others => '0'),
		DCLK                => clk200_int,
		DEN                 => '0',
		DI(15 downto 0)     => (others => '0'),
		DWE                 => '0',
		RESET               => '0',
		VAUXN(15 downto 0)  => (others => '0'),
		VAUXP(15 downto 0)  => (others => '0'),
		ALM                 => open,
		BUSY                => open,
		CHANNEL             => open,
		DO(15 downto 0)     => open,
		DRDY                => open,
		EOC                 => open,
		EOS                 => open,
		JTAGBUSY            => open,
		JTAGLOCKED          => open,
		JTAGMODIFIED        => open,
		OT                  => open,
		MUXADDR             => open,
		VN                  => '0',
		VP                  => '0'
	);

	addr <= unsigned(ctl_addr(20 downto 2));

	---------------------------------------------------------------------
	-- Core control registers
	---------------------------------------------------------------------

	bus_if: process(clk125_int)
		variable ipif_dout_var: std_logic_vector(31 downto 0);
	begin
		if rising_edge(clk125_int) then
			-- Combine data buses (inactive buses are set to '0' so they can all be combined with 'or')
			ipif_dout_var := dout(0);
			for i in 1 to NUMBER_OF_MODULES-1 loop
				ipif_dout_var := ipif_dout_var or dout(i);
			end loop;

			ctl_dout <= ipif_dout_var;
			ctl_rack <= or_reduce(rack);
			ctl_wack <= or_reduce(wack);

			-- clear request to all modules by default
			rreq <= (others=>'0');
			wreq <= (others=>'0');

			-- set the rreq and wreq if the currently addressed module.
			rreq(to_integer(addr(18 downto 14))) <= ctl_rreq;
			wreq(to_integer(addr(18 downto 14))) <= ctl_wreq;

			-- Because we generate module requests with a
			-- clock cycle's worth of delay, we should also
			-- latch data and address inputs.
			addr_dly <= addr;
			din_dly <= ctl_din;

			------------------------------------------------
			-- BASE MEMORY-MAPPED REGISTERS
			------------------------------------------------

			-- Immediately ack any requests.
			-- Note that the ack is delayed by one clock, so back-to-back writes are not possible.
			wack(BASE_ADDR) <= wreq(BASE_ADDR);
			rack(BASE_ADDR) <= rreq(BASE_ADDR);

			-- Make sure that dout is 0 when not used to allow 'or' combining of all module buses
			dout(BASE_ADDR) <= (others => '0'); --! important!
			-- Process Reads
			if rreq(BASE_ADDR)='1' then
				case to_integer(addr_dly(4 downto 0)) is --! Last 10 bits of address is used to index base registers
					when 0 => dout(BASE_ADDR) <= x"beefface"; -- Core firmware cookie
					when 1 => dout(BASE_ADDR) <= APPLICATION_COOKIE; -- Application firmware cookie
					when 2 => dout(BASE_ADDR) <= APPLICATION_FLAGS; -- Application Flags: Kintex 7
					when 3 => dout(BASE_ADDR) <= firmware_crc32; -- Firmware CRC32, computed by the host application and stored here for future reference
					when others => -- nop
				end case;
			end if;

			-- Writes
			if wreq(BASE_ADDR)='1' then
				case to_integer(addr_dly(4 downto 0)) is
					when 3 => firmware_crc32 <= din_dly;
					when others => -- nop
				end case;
			end if;

		end if; -- clk125
	end process;

end IMPL;
