/*
* Header for ctimestream_receiver.c
 */

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <netdb.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <time.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <errno.h>
#include <signal.h>

#define NPROD_PER_CMAC = 512 // Number of products generated by each CMAC
#define PROD_SIZE = 5 // Number of bytes in an integrated product
#define CORR_HEADER_SIZE = 12 // Number of bytes in a correlator packet header
#define CORR_PACKET_SIZE PROD_SIZE*NPROD_PER_CMAC + CORR_HEADER_SIZE // Correlator packet payload size (header + data)
#define NCMAC 34 // Number of CMACs per correlator
#define NCOR  8 // Number of correlators
#define nsamples 2048 // Number of time samples per raw data packets
#define nantenna 16
#define nprod = nsamples * (nsamples + 1) / 2
#define CORRELATOR_FRAME_ID = 0xBF;

/*
 * error - wrapper for perror
 */
void error(char *msg);

void sig_handler(int sigNumber);

typedef struct {
    int32_t real;  /* Real part */
    int32_t imag;  /* Imaginary part */
  } complex_t;

// Structure to hold the assembled set of correlator packets that represent the full correlator frame
typedef struct accumulation
 {
  uint32_t timestamp;
  uint8_t data[NCMAC][NCOR][BUFSIZE]; /* message buf */
  uint8_t received_list[NCMAC][NCOR]; /* received frame list */

 } accFrame;

typedef struct spectrum
 {
  uint32_t timestamp;
  int8_t timestream[nantenna][nsamples];
 } singleTime;




int cget_corr_frame(accFrame *frame, char *port, int verbose);

int cget_frame(singleTime *singleTimestamp, char *port, int number_channels, int verbose);
