#include "iceboard_constants.h"
#include "tuber.h"
#include "runtime.h"

/* Categories for tuber_methods */
const char *CATEGORY_ICEBOARD = "IceBoard";
const char *CATEGORY_MEZZANINE = "Mezzanine";
const char *CATEGORY_BACKPLANE = "Backplane";

/* Units */
const char *HZ="Hz";
const char *RAW="RAW";
const char *VOLTS="Volts";
const char *AMPS="Amps";
const char *WATTS="Watts";
const char *DAC_COUNTS="DAC Counts";
const char *ADC_COUNTS="ADC Counts";
const char *NORMALIZED="Normalized";
const char *DEGREES="Degrees";
const char *RADIANS="Radians";
const char *OHMS="Ohms";

#ifdef LIBTUBER
tuber_property(IceBoard, UNITS, json_pack(
		"{"
		" s:s, s:s, s:s, s:s, s:s,"
		" s:s, s:s, s:s, s:s, s:s,"
		" s:s "
		"}",
		"HZ", HZ,
		"RAW", RAW,
		"VOLTS", VOLTS,
		"AMPS", AMPS,
		"WATTS", WATTS,
		"DAC_COUNTS", DAC_COUNTS,
		"ADC_COUNTS", ADC_COUNTS,
		"NORMALIZED", NORMALIZED,
		"DEGREES", DEGREES,
		"RADIANS", RADIANS,
		"OHMS", OHMS
));
#endif

/* Temperature sensors */
const char *MOTHERBOARD_TEMPERATURE_POWER = "MOTHERBOARD_TEMPERATURE_POWER";
const char *MOTHERBOARD_TEMPERATURE_ARM = "MOTHERBOARD_TEMPERATURE_ARM";
const char *MOTHERBOARD_TEMPERATURE_FPGA = "MOTHERBOARD_TEMPERATURE_FPGA";
const char *MOTHERBOARD_TEMPERATURE_FPGA_DIE = "MOTHERBOARD_TEMPERATURE_FPGA_DIE";
const char *MOTHERBOARD_TEMPERATURE_PHY = "MOTHERBOARD_TEMPERATURE_PHY";

const char *BACKPLANE_TEMPERATURE_SLOT1 = "BACKPLANE_TEMPERATURE_SLOT1";
const char *BACKPLANE_TEMPERATURE_SLOT16 = "BACKPLANE_TEMPERATURE_SLOT16";

#ifdef LIBTUBER
tuber_property(IceBoard, TEMPERATURE_SENSOR, json_pack(
		"{"
		" s:s, s:s, s:s, s:s, s:s, s:s, s:s"
		"}",
		"MB_POWER", MOTHERBOARD_TEMPERATURE_POWER,
		"MB_ARM", MOTHERBOARD_TEMPERATURE_ARM,
		"MB_FPGA", MOTHERBOARD_TEMPERATURE_FPGA,
		"MB_FPGA_DIE", MOTHERBOARD_TEMPERATURE_FPGA_DIE,
		"MB_PHY", MOTHERBOARD_TEMPERATURE_PHY,
		"BP_SLOT1", BACKPLANE_TEMPERATURE_SLOT1,
		"BP_SLOT16", BACKPLANE_TEMPERATURE_SLOT16
));
#endif

/* Motherboard power rails */
const char *MOTHERBOARD_RAIL_VCC3V3 = "MOTHERBOARD_RAIL_VCC3V3";
const char *MOTHERBOARD_RAIL_VCC12V0 = "MOTHERBOARD_RAIL_VCC12V0";
const char *MOTHERBOARD_RAIL_VCC5V5 = "MOTHERBOARD_RAIL_VCC5V5";
const char *MOTHERBOARD_RAIL_VCC1V0_GTX = "MOTHERBOARD_RAIL_VCC1V0_GTX";
const char *MOTHERBOARD_RAIL_VCC1V0 = "MOTHERBOARD_RAIL_VCC1V0";
const char *MOTHERBOARD_RAIL_VCC1V2 = "MOTHERBOARD_RAIL_VCC1V2";
const char *MOTHERBOARD_RAIL_VCC1V5 = "MOTHERBOARD_RAIL_VCC1V5";
const char *MOTHERBOARD_RAIL_VCC1V8 = "MOTHERBOARD_RAIL_VCC1V8";
const char *MOTHERBOARD_RAIL_VADJ = "MOTHERBOARD_RAIL_VADJ";

/* Mezzanine power rails */
const char *MEZZANINE_RAIL_VCC3V3 = "MEZZANINE_RAIL_VCC3V3";
const char *MEZZANINE_RAIL_VCC12V0 = "MEZZANINE_RAIL_VCC12V0";
const char *MEZZANINE_RAIL_VADJ = "MEZZANINE_RAIL_VADJ";

#ifdef LIBTUBER
tuber_property(IceBoard, RAIL, json_pack(
		"{"
		" s:s, s:s, s:s, s:s, s:s"
		" s:s, s:s, s:s, s:s, s:s"
		" s:s, s:s"
		"}",
		"MB_VCC3V3", MOTHERBOARD_RAIL_VCC3V3,
		"MB_VCC12V0", MOTHERBOARD_RAIL_VCC12V0,
		"MB_VCC5V5", MOTHERBOARD_RAIL_VCC5V5,
		"MB_VCC1V0_GTX", MOTHERBOARD_RAIL_VCC1V0_GTX,
		"MB_VCC1V0", MOTHERBOARD_RAIL_VCC1V0,
		"MB_VCC1V2", MOTHERBOARD_RAIL_VCC1V2,
		"MB_VCC1V5", MOTHERBOARD_RAIL_VCC1V5,
		"MB_VCC1V8", MOTHERBOARD_RAIL_VCC1V8,
		"MB_VADJ", MOTHERBOARD_RAIL_VADJ,
		"MEZZ_VCC3V3", MEZZANINE_RAIL_VCC3V3,
		"MEZZ_VCC12V0", MEZZANINE_RAIL_VCC12V0,
		"MEZZ_VADJ", MEZZANINE_RAIL_VADJ
));
#endif

#ifdef LIBTUBER
tuber_property(IceBoard, NUM_MEZZANINES, json_pack("i", NUM_MEZZANINES));
#endif

const char *CLOCK_SOURCE_XTAL = "CLOCK_SOURCE_XTAL";
const char *CLOCK_SOURCE_SMA = "CLOCK_SOURCE_SMA";
const char *CLOCK_SOURCE_BP = "CLOCK_SOURCE_BP";

#ifdef LIBTUBER
tuber_property(IceBoard, CLOCK_SOURCE, json_pack(
		"{"
		" s:s, s:s, s:s"
		"}",
		"XTAL", CLOCK_SOURCE_XTAL,
		"SMA", CLOCK_SOURCE_SMA,
		"BP", CLOCK_SOURCE_BP
));
#endif