--------------------------------------------------------------------------------
--! @file
--! @brief Top-level file to implement DFMUX on the Kintex 7 McGill MGK7MB platform
-- Company: McGill University
-- Engineer: JF Cliche and Graeme Smecher
--
-- Create Date: 2013-06-12
-- Design Name: dfmux_mgk7mb_mgmezz04
-- Module Name: top - Behavioral
-- Project Name: DFMUX
-- Target Devices: Kintex 7 on Mggill MGK7MB board
-- Tool versions: Vivado 2014.1

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

library UNISIM;
use UNISIM.VComponents.all;

library work;
use work.icecore_package.all;

----ENTITY DECLARATION ---------------------------------------------------------

entity iceboard_top_example is
	GENERIC (
		-- Clocking configuration
		MASTER_CLOCK_SOURCE : string  := "SFP125"; -- use the SFP+ GTX 125 MHz reference  clock to generate all the internal clocks
		CLOCK_SOURCE        : string  := "REFCLK"; --! "CLK125" uses clk125 from the main MMCM; "REFCLK": uses the GTX Reference clock (gtrefclk)
		SIM                 : boolean := FALSE --! Used to accelerate simulation.
	);
	PORT (
		-- ARM <-> FPGA SPI port
		arm_spi_sck : in std_logic;
		arm_spi_miso : out std_logic;
		arm_spi_mosi : in std_logic;
		arm_spi_cs_n : in std_logic;

		------------------------------------
		-- ARM PCIe / SFP (Gbit Ethernet)
		-- We use the PCIe/SFP 125 MHz reference clock as a system clock
		------------------------------------
		sfp_clk125_p : in std_logic;
		sfp_clk125_n : in std_logic;

		------------------------------------
		-- SYSTEM
		------------------------------------

		-- Reset line
		cpu_reset_n: in std_logic; --! Active-low asynchronous hardware reset generated by the board

		-- Iceboard and backplane I/O
		sma_a :                out std_logic; -- SMA_A connector
		sma_b_fpga_led2 :      out std_logic; -- SMA_B connector and FPGA_LED2
		fpga_led1 :            out std_logic; -- FPGA LED1
		bp_time_p, bp_time_n : in std_logic; -- Time signal distributed by the backplane (LVDS)

		-- IceBoard Buck sync lines
		sync_1v0 : out std_logic;
		sync_1v8 : out std_logic;
		sync_1v0_gtx : out std_logic;
		sync_5v0 : out std_logic;
		sync_1v2 : out std_logic;
		sync_vadj : out std_logic;
		sync_1v5 : out std_logic;
		sync_3v3 : out std_logic;
		sync_12v0 : out std_logic
	);
end iceboard_top_example;

architecture IMPL of iceboard_top_example is

	signal clk200: std_logic;
	signal cpu_reset_int: std_logic;

	signal irig_bp : std_logic;
	signal arm_spi_miso_int: std_logic;

begin

irig_bp_ibuf : IBUFDS port map (
	I => bp_time_p,
	IB => bp_time_n,
	O => irig_bp
);

cpu_reset_int <= not cpu_reset_n;

sma_a <= arm_spi_sck;
sma_b_fpga_led2 <= arm_spi_miso_int;
arm_spi_miso <= arm_spi_miso_int;

icecore0: entity work.icecore
	generic map (
		MASTER_CLOCK_SOURCE => MASTER_CLOCK_SOURCE,
		IMPLEMENT_TIMESTAMP => FALSE,
		SIM                 => SIM
	) port map (
		arm_spi_sck => arm_spi_sck,
		arm_spi_miso => arm_spi_miso_int,
		arm_spi_mosi => arm_spi_mosi,
		arm_spi_cs_n => arm_spi_cs_n,

		sync_1v0     => sync_1v0,
		sync_1v8     => sync_1v8,
		sync_1v0_gtx => sync_1v0_gtx,
		sync_5v0     => sync_5v0,
		sync_1v2     => sync_1v2,
		sync_vadj    => sync_vadj,
		sync_1v5     => sync_1v5,
		sync_3v3     => sync_3v3,
		sync_12v0    => sync_12v0,

		-- Timestamps
		irig_bp => irig_bp,
		irig_sma => irig_bp,

		-- SFP Ethernet interface ports
		sfp_clk125_p => sfp_clk125_p,
		sfp_clk125_n => sfp_clk125_n,

		-- I/O logic interface
		clk200 => clk200,

		-- System
		cpu_reset => cpu_reset_int
	);

end IMPL;
