--------------------------------------------------------------------------------
--! @file
--! @brief Top-level file to implement DFMUX on the Kintex 7 McGill MGK7MB platform
-- Company: McGill University
-- Engineer: JF Cliche and Graeme Smecher
--
-- Create Date: 2013-06-12
-- Design Name: dfmux_mgk7mb_mgmezz04
-- Module Name: top - Behavioral
-- Project Name: DFMUX
-- Target Devices: Kintex 7 on Mggill MGK7MB board
-- Tool versions: Vivado 2014.1

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

library UNISIM;
use UNISIM.VComponents.all;

library work;
use work.icecore_package.all;

----ENTITY DECLARATION ---------------------------------------------------------

entity iceboard_top_example is
	GENERIC (
		-- Clocking configuration
		MASTER_CLOCK_SOURCE : string  := "SFP125"; -- use the SFP+ GTX 125 MHz reference  clock to generate all the internal clocks
		CLOCK_SOURCE        : string  := "REFCLK"; --! "CLK125" uses clk125 from the main MMCM; "REFCLK": uses the GTX Reference clock (gtrefclk)
		SIM                 : boolean := FALSE --! Used to accelerate simulation.
	);
	PORT (
		-- ARM <-> FPGA SPI port
		arm_spi_sck : in std_logic;
		arm_spi_miso : out std_logic;
		arm_spi_mosi : in std_logic;
		arm_spi_cs_n : in std_logic;

		------------------------------------
		-- ARM PCIe / SFP (Gbit Ethernet)
		-- We use the PCIe/SFP 125 MHz reference clock as a system clock
		------------------------------------
		sfp_clk125_p : in std_logic;
		sfp_clk125_n : in std_logic;

		------------------------------------
		-- SYSTEM
		------------------------------------

		-- Reset line
		cpu_reset_n: in std_logic; --! Active-low asynchronous hardware reset generated by the board

		-- Iceboard and backplane I/O
		sma_a :                out std_logic; -- SMA_A connector
		sma_b_fpga_led2 :      out std_logic; -- SMA_B connector and FPGA_LED2
		fpga_led1 :            out std_logic; -- FPGA LED1
		bp_time_p, bp_time_n : in std_logic; -- Time signal distributed by the backplane (LVDS)

		-- IceBoard Buck sync lines
		sync_1v0 : out std_logic;
		sync_1v8 : out std_logic;
		sync_1v0_gtx : out std_logic;
		sync_5v0 : out std_logic;
		sync_1v2 : out std_logic;
		sync_vadj : out std_logic;
		sync_1v5 : out std_logic;
		sync_3v3 : out std_logic;
		sync_12v0 : out std_logic
	);
end iceboard_top_example;

architecture IMPL of iceboard_top_example is

	signal clk200: std_logic;
	signal clk125: std_logic; -- Clock used for the internal data bus
	signal cpu_reset_int: std_logic;

	signal irig_bp : std_logic;

	-- Bus interface
	signal core_addr : std_logic_vector(31 downto 0);
	signal core_rreq : std_logic;
	signal core_rdat : std_logic_vector(31 downto 0);
	signal core_rack : std_logic;
	signal core_wreq : std_logic;
	signal core_wdat : std_logic_vector(31 downto 0);
	signal core_wack : std_logic;

	-- User application signals
	constant NUMBER_OF_USER_REGS: integer := 4;
	signal user_reg_wr_value : slv32_array(0 to NUMBER_OF_USER_REGS-1);
	signal user_reg_rd_value : slv32_array(0 to NUMBER_OF_USER_REGS-1);

	signal op1: unsigned(31 downto 0);
	signal op2: unsigned(31 downto 0);
	signal sum: unsigned(31 downto 0);

begin

irig_bp_ibuf : IBUFDS port map (
	I => bp_time_p,
	IB => bp_time_n,
	O => irig_bp
);

cpu_reset_int <= not cpu_reset_n;


icecore0: entity work.icecore
	generic map (
		MASTER_CLOCK_SOURCE => MASTER_CLOCK_SOURCE,
		IMPLEMENT_TIMESTAMP => FALSE,
		SIM                 => SIM
	) port map (
		arm_spi_sck => arm_spi_sck,
		arm_spi_miso => arm_spi_miso,
		arm_spi_mosi => arm_spi_mosi,
		arm_spi_cs_n => arm_spi_cs_n,

		-- Buck sync
		sync_1v0     => sync_1v0,
		sync_1v8     => sync_1v8,
		sync_1v0_gtx => sync_1v0_gtx,
		sync_5v0     => sync_5v0,
		sync_1v2     => sync_1v2,
		sync_vadj    => sync_vadj,
		sync_1v5     => sync_1v5,
		sync_3v3     => sync_3v3,
		sync_12v0    => sync_12v0,

		-- Timestamps
		irig_bp => irig_bp,
		irig_sma => irig_bp,

		-- SFP Ethernet interface ports
		sfp_clk125_p => sfp_clk125_p,
		sfp_clk125_n => sfp_clk125_n,


		-- Master Bus interface
		m_addr => core_addr,
		m_rdat => core_rdat,
		m_wdat => core_wdat,
		m_rreq => core_rreq,
		m_rack => core_rack,
		m_wreq => core_wreq,
		m_wack => core_wack,

		-- I/O logic interface
		clk200 => clk200,
		clk125 => clk125,

		-- System
		cpu_reset => cpu_reset_int
	);

------------------------------------------------
-- USER APPLICATION EXAMPLE
------------------------------------------------
-- Our application example consist in software-controlled LEDS and a simple 32-bit adder.
-- The application is controller by a set of registers that can be read/written by the Python application handler.
-- If we had a larger application, we could instantiate another bus_interconnect entity to split the bus to any number of submodules

-----------------------------------------------------
-- Software-controlled Registers
-----------------------------------------------------

--! Register map
--! =============
--! Base address: 0x00000100. Addresses below are offset from this base address.
--!  --------------------------------------------------------------------------------
--! | Reg #   | Addr |Bit(s)| Signal name                 | R/W       | Description |
--! |---------|------|------|-----------------------------|-----------|-------------|
--! | 0       | 0x00 | 31-3 | Unused                      | Readback  |             |
--! |         |      |  2   | sma_a                       | Readback  | Sets the logic level on the SMA A connector.|
--! |         |      |  1   | sma_b_fpga_led2             | Readback  | Sets the state of the FPGA LED2 and the logic level on SMA B connector |
--! |         |      |  0   | fpga_led1                   | Readback  | Sets the state of the FPGA LED1 |
--! | 1       | 0x04 | 31-0 | op1                         | Readback  | First operand of the adder|
--! | 2       | 0x08 | 31-0 | op2                         | Readback  | Second operand of the adder|
--! | 3       | 0x0C | 31-0 | sum                         | Read-only | Output of the adder|
--!  ------------------------------------------------------------------------------
--!
-- Registers - write direction
-- These are the value that are written to the registers by the software
-- Here we assign the register values to meaningfully-named signals that will be used by our application
fpga_led1 <= user_reg_wr_value(0)(0);
sma_b_fpga_led2 <= user_reg_wr_value(0)(1);
sma_a <= user_reg_wr_value(0)(2);
op1 <= unsigned(user_reg_wr_value(1));
op2 <= unsigned(user_reg_wr_value(2));

-- Registers - read direction
-- These are the values that are read by the software
--
-- It is highly recommended to have registers read back the last value written
-- to them whenever possible, especially in registers where we might want to
-- control intividual bits.
user_reg_rd_value(0) <= user_reg_wr_value(0); -- read last value written
user_reg_rd_value(1) <= user_reg_wr_value(1); -- read last value written
user_reg_rd_value(2) <= user_reg_wr_value(2); -- read last value written
user_reg_rd_value(3) <= std_logic_vector(sum);


-- We instantiate a bank of registers starting at address 0x00000100
app_regs0: entity work.register_array
	generic map(
		ADDRESS_MASK => X"000001" & "------XX", -- up to 64 registers starting at 0x0000_0100
		NUMBER_OF_REGISTERS => NUMBER_OF_USER_REGS,
		DEFAULT_REGISTER_VALUES => (0 to NUMBER_OF_USER_REGS-1 => X"AAAAAAAA"),
		ADDRESS_WIDTH => 32,
		SIM => SIM --! Indicates this is running as a simulation. Used to accelerate simulations
	)
	port map (
		-- Control interface (*** JFC: to be replaced by an AXI4-Lite bus)
		s_addr => core_addr,
		s_wdat => core_wdat,
		s_wreq => core_wreq,
		s_rreq => core_rreq,
		s_wack => core_wack,
		s_rdat => core_rdat,
		s_rack => core_rack,

		-- Register interface
		reg_wr_value  => user_reg_wr_value,
		reg_rd_value  => user_reg_rd_value,

		clk => clk125 -- Clocks both control and register interface
	);

-----------------------------------------------------
-- A32-bit adder
-----------------------------------------------------

sum_proc: process(clk125)
begin
	if rising_edge(clk125) then
		sum <= op1 + op2;
	end if;
end process;

end IMPL;
