# Crate commissioning tests
# 
# Define the following to the setup being tested
#    power supply: instruments.ps.adapter
#    hardware map: f_engine_tests.global_settings.fpga_array_params.hwm
#
#
# model_number required to run the tests (generate data folder name, configure EEPROM etc.). Not sure if this is the correct one
# to use for the F-Engine tests, but using it for now.
model_number: 'MGK7BP16'

fpga_bit_file: '../../pychfpga/fpga_firmware/bitstreams/chFPGA_MGK7MB_Rev2.bit'

instruments:
  # ps:     {labpy_object: 'agilent_N5700', adapter: 'TCPIP::10.10.10.115'}  # Agilent N5764A power supply, McGill kitchen rack top
  ps:     {labpy_object: 'agilent_N5700', adapter: 'TCPIP::10.10.10.234'}  # Agilent N5764A power supply, McGill kitchen rack bottom
  # ps:     {labpy_object: 'agilent_N5700', adapter: 'TCPIP::10.42.200.54'} # Agilent power supply, GBO-F-Engine in McGill FRB testbed
?: &default_fpga_array # Shouldn't really be used
    iceboards: 0047
    mdns_delay: 1

##################################################
test_results_folder: '~/test_results'  # relative to this config file's folder. "~" is allowed.
#test_results_folder_uses_git: false
#xml_test_results_pathname: "~/test_results"  # not needed for a pure menu
##################################################


test_list:
    # This list all the tests that will be done by the test software, in the proper order
    # path is the argument given to nose to find the test fucntion, in the form of module_path:function or module_path:class.method
    # This path is also the path used by XReport to identify tests results, with the exception that the semicolon ':' is replaced by a dot '.'
    ps:      {description: 'Power supply connection test',  path: 'f_engine_tests.py::TestPreDeploymentCrate::test_ps_connection',  required: yes, require_serial_number: yes, dependencies: null}
    init:    {description: 'Crate initialization test',     path: 'f_engine_tests.py::TestPreDeploymentCrate::test_init',           required: yes, require_serial_number: yes, dependencies: null}
    bperr:   {description: 'Backplane error test',          path: 'f_engine_tests.py::TestPreDeploymentCrate::test_bperr',          required: yes, require_serial_number: yes, dependencies: null}
    sync:    {description: 'Sync test',                     path: 'f_engine_tests.py::TestPreDeploymentCrate::test_sync',           required: yes, require_serial_number: yes, dependencies: null}
    clock:   {description: 'ADC clock test',                path: 'f_engine_tests.py::TestPreDeploymentCrate::test_adc_clocks',     required: yes, require_serial_number: yes, dependencies: null}
    syncdel: {description: 'ADC sync delays test',          path: 'f_engine_tests.py::TestPreDeploymentCrate::test_sync_delays',    required: yes, require_serial_number: yes, dependencies: null}
    eye:     {description: 'ADC eye test',                  path: 'f_engine_tests.py::TestPreDeploymentCrate::test_adc_eye',        required: yes, require_serial_number: yes, dependencies: null}
    cycle:   {description: 'Power cycle test',              path: 'f_engine_tests.py::TestPreDeploymentCrate::test_power_cycle',    required: yes, require_serial_number: yes, dependencies: null}
    network: {description: 'Network connection test',       path: 'f_engine_tests.py::TestPreDeploymentCrate::test_network',        required: yes, require_serial_number: yes, dependencies: null}
    ramp:    {description: 'Crate level ramp test',         path: 'f_engine_tests.py::TestPreDeploymentCrate::test_crate_ramp',     required: yes, require_serial_number: yes, dependencies: null}

menu:
    # The menu item will match the user input to either the 'key' field or to the regular expression 'regex'. The matching dictionary is returned.
    # If a regular expression is given, string parameters are replaced by string_param.format(regex_matched_group_list), i.e. '{0}' is replaced by the first matched group etc. The 'key' and 'regex' fields are excluded from this conversion.
    # Entry types are:
    #  test: a test to run. test_tag refers to the test to run in test_list (defined above). A regex entry will be added to match the tets tag and tets path. The description will be taken from the test description if none is provided here.
    #  exit: exit the menu
    #  text: do nothing. The description is shown in the menu if there is one.
    #  board_info: Sets the current board model and serial number. The serial number can be extracted from string parsed by the regex
    #
    - { description: "Start by entering the BP's serial number, then select a test or range of tests (e.g. 2-4).",     type: text}
    - { key: '0',                    action: run_test, test_tag: ps}
    - { key: '1',                    action: run_test, test_tag: init}
    - { key: '2',                    action: run_test, test_tag: bperr}
    - { key: '3',                    action: run_test, test_tag: sync}
    - { key: '4',                    action: run_test, test_tag: clock}
    - { key: '5',                    action: run_test, test_tag: syncdel}
    - { key: '6',                    action: run_test, test_tag: eye}
    - { key: '7',                    action: run_test, test_tag: cycle}
    - { key: '8',                    action: run_test, test_tag: network}
    - { key: '9',                    action: run_test, test_tag: ramp}
    - { key: 'S',                    action: push,    description: 'Send all new test results data to McGill'}
    - { key: 'R',                    action: summary, description: 'Generate summary of all tests'           }
    - { key: 'Q',                    action: exit,    description: 'Exit'                                    }
    - { regex: '(0\d{2})', model: 'MGK7BP16', serial: '{0}', next_key: '0'}  # 0nn are MGK7BP16 Serial number
    - { regex: '\d+\-\d+', action: run_range, input: '{0}'} # regex to select a range of options

##################################
# Test-specific parameters
##################################
f_engine_tests:
  global_settings:
    eth_interface: 'eno1' # Check if correct. Name of ethernet interface on which the crate is connected. Used to check jumbo frames.
    ps_voltage: 20  # Volts. Voltage to set on the F-Engine power supply
    ps_current: 76   # Amps. Maximum current limit to set on the F-Engine power supply
    ps_t_sleep: 60 # Time in seconds to let the power supply sleep upon power cycle to allow crate to boot
    fpga_array_params:
      # hwm: 'bp16 25:0' # McGill kitchen test rack top
      hwm: 'bp16 29:0' # McGill kitchen test rack bottom
      # hwm: 'bp16 33:0' # GBO-F-Engine in McGill FRB testbed
      # hwm: 'bp16 32:0' # HCO-F-Engine
      # hwm:
              #  - {class: "IceCrate_MGK7BP16", serial: "032", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.39", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.38", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.37", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.40", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.41", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.45", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.42", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.43", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.44", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.46", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.52", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.48", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.49", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.51", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.56", crate_number: 0}
                 #- {class: "IceBoard", hostname: "10.42.200.50", crate_number: 0}
      stderr_log_level: 'info'
      prog: 2
      #mode: 'shuffle128' # only for KKO F-Engine
      #ignore_missing_boards: True # only for KKO F-Engine
      mode: 'shuffle256' # All else
      sync_method: 'irigb'
      mdns_timeout: 40


  ps_connection_test:
    n_ps_cycles: 50  
    on_time: 120 #seconds
    off_time: 10
        
  crate_init:

  backplane_err:
    n_checks: 10
    t_sleep: 1

  sync_test:
    n_syncs: 100

  network_test:
    n_cycles: 10
    t_cycle: 5
    fpga_array_params:
      hwm: 'bp16 29:0' # McGill kitchen test rack

      stderr_log_level: 'info'
      prog: 0
      open: 0
      #mode: 'shuffle128' # only for KKO F-Engine
      ignore_missing_boards: False # only for KKO F-Engine
      mode: 'shuffle256' # All else
      sync_method: 'local'
      mdns_timeout: 20

  clock_test:
    integration_period: 0.001
    n_clock_checks: 10
    n_cycles: 5
    powerup_delay: 5

  sync_delay_test:

  adc_eye_test:
    n_checks: 50
    n_refs: 25
    n_fails_accept: 5
    max_spread: 16

  p_cycle_test:
    # n_cycles: 20 
    n_cycles: 100 
    percent_accept: 0.05 #0.01
    t_cycle: 10  #time in seconds

  power_clock_test:
    n_cycles: 100 
    percent_accept: 0.05 #0.01
    t_cycle: 10  #time in seconds

  ramp_test:
    n_checks: 1
