[pytest]
addopts = --capture=tee-sys --xreport-path="../../../qc_results/{model}/{model}_SN{serial}/{isodate}_{session_name}.xml"

# needed to include all stdout text into the xml report

junit_logging = all

